### ISSUE TITLE
Guzzle request to cloudflare-protected server

### ISSUE THREAD

**Issue by ErickSkrauch** [guzzle/guzzle#1000]
Hi.

When i try to make request for server, that use cloudflare protection, i gave this funny thing:

```
Server error response [url] http://siteurl.com/ [status code] 503 [reason phrase] Service Temporarily Unavailable
```

It's okay, because response really have 503 status, but what about passing cloudflare protection - is it possible?

**Comment by mtdowling** [comment]
What is Cloudflare protection? Do you pass some auth header or something?

**Comment by ErickSkrauch** [comment]
[Cloudflare](https://www.cloudflare.com/). This is CDN hosting with DDOS protection service.

**Comment by mtdowling** [comment]
Yes, my question is what is their mechanism for "protecting" a website? What are the technical requirements of this issue?

**Comment by ErickSkrauch** [comment]
I think they set some cookies for user, but i didn't understand mechanism fully.

It looks like this: you go to their page on which you hold for 5 seconds, after which there js-redirect to the main site.

**Comment by mtdowling** [comment]
Ah. Guzzle is only an HTTP client, so it will not follow things like JS redirects or HTML meta redirects.

**Comment by ErickSkrauch** [comment]
Can have any advice to solve my problem as an alternative?

**Comment by mtdowling** [comment]
If it's a JavaScript solution, then I have no idea. If it's an HTML meta tag, then you could parse the response body, check for the tag, and send a followup request to the location.

Here's a stackoverflow post I found that might help you: http://stackoverflow.com/questions/11886711/curl-cant-fetch-rss-from-website-because-of-cloudflare

**Comment by ErickSkrauch** [comment]
Thanks for post.

**Comment by allella** [comment]
Similar problem.

Got a cURL error 35 from Guzzle so I looked at the SSL certificate for the requested URL and see it's hosted by CloudFlare (the SSL certificate's primary Subject is a cloudflare sub-domain).  Presumably it's recognizing that I'm a PHP script and not a web browser.

Someone suggests one potential temporary way to do cURL requests to Cloudflare protection, but it would likely need to be extended further to allow for it to without human intervention.

http://stackoverflow.com/questions/18500088/curl-load-a-site-with-cloudflare-protection

**Comment by allella** [comment]
Actually, the issue could simply be the version of cURL on stock CentOS 6.5, or that plus some other factor about the Cloudflare configuration.

http://www.webhostingtalk.com/showthread.php?t=1421536&p=9267093#post9267093

`curl -1IsS https://sslspdy.com`

CentOS 6.5 fails on the test above
curl 7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.19.1 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2

whereas the same test runs fine on CentOS 7 with
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.19.1 Basic ECC zlib/1.2.7 libidn/1.28 libssh2/1.4.3

**Comment by allella** [comment]
There appear to be multiple issues.

**Problem 1**
A cURL error 35 on CentOS 6 is due to the stock version of cURL.
This post suggested the issue http://www.webhostingtalk.com/showthread.php?t=1421536&p=9267093#post9267093

To test run

`curl -1IsS https://sslspdy.com`

The stock CentOS 6.* fails on the test above with the stock libcurl 7.19.7

The same test runs fine on stock CentOS 7 with libcurl 7.29.0

CentOS 6.7 with the newer cURL (libcurl 7.48.0) installed via commands below gets rid of the error 35.

`rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-13.rhel6.noarch.rpm
yum install libcurl`

kudos to http://blogs.reliablepenguin.com/2015/08/20/upgrade-curl

**Problem 2**
Once the newer version of cURL is installed Guzzle no longer returns an error 35, but no returns

`cURL error 56: Recv failure: Connection reset by peer`

Other SSL connections work fine and only the Cloudflare connection errors out.

It sounds like it could be Cloudflare's bot protection rejecting the cURL requests for not having an expected cookie value. Though, this is still not 100% confirmed.

http://stackoverflow.com/questions/18500088/curl-load-a-site-with-cloudflare-protection

**Comment by tunaabutbul** [comment]
just use my middleware: https://github.com/tunaabutbul/cloudflare-middleware
