### ISSUE TITLE
Method GuzzleHttp\Stream\Stream::__toString() must not throw an exception

### ISSUE THREAD

**Issue by slbmeh** [guzzle/guzzle#1018]
At some point between request creation and actually sending the request my resource becomes stale. Every step shows the type as a stream until the __toString call the type is unknown throwing an exception when performing stream operations.

**Comment by slbmeh** [comment]
Ah, I see. It's happening when my signature subscriber clones the stream.  What is a good way to get the stream contents to hash the body on a stream that is not seekable? Wrap the stream get contents in stream factory if it is not and set the body to the new stream?

**Comment by mtdowling** [comment]
What do you mean by "the type is unknown"? Is there an exception that's thrown or a warning message?

**Comment by slbmeh** [comment]
`var_dump($this->stream)` tells me resource, the identifier, and tells me stream... after I clone it `var_dump($this->stream)` tells me resource, identifier doesn't change, but the type says `Unknown`  I'm getting an exception that stems from the stream operations on the resource. I haven't checked to see if it was an error translated to an exception.

**Comment by mtdowling** [comment]
> What is a good way to get the stream contents to hash the body on a stream that is not seekable?

Reading from a stream that is not seekable will consume the stream such that you cannot subsequently read from the stream (i.e., reading to hash the stream will prevent you from reading from the stream to send it in an HTTP request).

You'll need to either load the stream into memory or decorate the stream with a CachingStream so that previously read bytes are stored in a buffer and recalled later if necessary: https://github.com/guzzle/streams/blob/master/src/CachingStream.php

**Comment by slbmeh** [comment]
Ah, decorating it works. Thank you.
