### ISSUE TITLE
Add constants for map key configuration options

### ISSUE THREAD

**Issue by Rican7** [guzzle/guzzle#1019]
Guzzle uses a lot of arrays for configuration, even just a basic client construction with a base URL requires the use of a map-style array with a `base_url` key.

Unfortunately, using basic strings like this is more prone to runtime errors than using a proper parameter or at least using a constant defining the configurable array key, as PHP doesn't have named parameter support. As using a named-parameter approach seems to be part of the design of this library and changing that would be a massive BC break, I suggest simply defining constants for the many array keys so that implementations could more easily use the library without having to worry about simple spelling mistakes at runtime or having to test otherwise simple constructors (yes 100% code coverage is ideal, but not always realistic).

An example:

```php
namespace GuzzleHttp;

class Client implements ClientInterface
{

    /**
     * The configuration key for the base URL configuration
     *
     * @type string
     */
    const CONFIG_KEY_BASE_URL = 'base_url';
}

**Comment by mtdowling** [comment]
I'd be happy to add something like this to v6 (which is in a branch and developing slowly as PSR-7 unfolds). I'm not sure if I'd want the constants under the GuzzleHttp namespace (e.g., `GuzzleHttp\CFG_TIMEOUT` or under a class in the namespace (e.g., `GuzzleHttp\RequestOptions::TIMEOUT`). The former is nice because it's shorted, the latter could be imported though (i.e., `use GuzzleHttp\RequestOptions as RO`), but that use import is a bit cumbersome IMO... Any thoughts?

**Comment by Rican7** [comment]
Awesome. :)

Hmm, importing ("using"/aliasing) a name-spaced constant isn't easily available until PHP 5.6, so I'd probably make them class constants, personally. Class constants also allow for a bit easier way to group and document them.

**Comment by kamilsk** [comment]
How about "Configuration Object"?
```php
$client = new Client(
    (new ClientConfig())
        ->setBaseUrl('...')
        ->setSomethingElse('...')
);
```
If you want, you can implement the method `toArray()` (if Guzzle will not support this approach)

**Comment by mtdowling** [comment]
I'm not a big fan of the config object idea mainly because the client constructor (and request options applied to a request) should allow any arbitrary key value pairs. For example, in Guzzle 6, you can create middlewares that know how to handle specific key value pairs. Strictly validating these key value pairs to only allow specific values would be too limiting, and using a builder pattern would be more overhead and complication than I'd like.

I'm not usually a big fan of class constants to demarcate key value pair options, but I'm willing to add those in this case if it will help people.

**Comment by mtdowling** [comment]
Added to Guzzle 6 in https://github.com/guzzle/guzzle/commit/af9a195d9bf20c8f1df1b865a8ef8161776b5ed9
