### ISSUE TITLE
Feature Request : Allow access to raw data on Stream class.

### ISSUE THREAD

**Issue by rtconner** [guzzle/guzzle#1022]
Basically I want something that works the same as detach() .. but without the two lines of code that are below 

```
$this->stream = $this->size = $this->uri = null;
$this->readable = $this->writable = $this->seekable = false;
```
So maybe like a getRawStream() or something, that just returns the stream

```
    public function getRawStream()
    {
        $result = $this->stream;

        return $result;
    }
```

**Comment by mtdowling** [comment]
Adding this would break the stream abstraction and would leave the stream object in an inconsistent state (e.g., some stream decorators rely on this). By detaching the stream, you're telling Guzzle that Guzzle is no longer responsible for managing the stream and therefore Guzzle makes it no longer possible to use it. You'll need to recreate a new Guzzle stream in order to work with a detached PHP stream.

**Comment by rtconner** [comment]
Well can you allow me to pass in PHP methods to call upon the stream point? 

$row = $stream->call('fgetcsv');

**Comment by mtdowling** [comment]
That still breaks the abstraction because you are assuming that each Guzzle stream owns a PHP stream and assuming that invoking these methods on the stream directly will not affect the internal state of any decorators. If you really want to do this, you'll need to hold on to a reference of a PHP stream before wrapping it in a Guzzle stream.
