### ISSUE TITLE
Method to change/set the CookieJar of a Request?

### ISSUE THREAD

**Issue by paslandau** [guzzle/guzzle#1028]
Is there an easy way to change the `CookieJar` of a request? I'm using a number of proxy servers to scrape some websites and would like to change the `CookieJar` as well when I set the proxy of a request.

My current "workaround" looks like this:

- check if there's already a `Cookie` subscriber attached to the request
- if so, remove it
- create new `Cookie` subscriber
- attach `CookieJar` to new subscriber
- attach new subscriber to request

Simplified example code:
````php
$c = new Client();
$req = $c->createRequest("GET", "http://httpbin.org/get");

$emitter = $req->getEmitter();
// look for current subscriber
foreach ($emitter->listeners("complete") as $listener) {
    if (is_array($listener) && $listener[0] instanceof Cookie) {
        $emitter->detach($listener[0]);
    }
}
// create new Cookie subscriber
$jar = new CookieJar();
$cookie = new Cookie($jar);
// set new Cookie subscriber
$emitter->attach($cookie);
````
Works, but feels pretty ugly.

Please note that I do not have no control over the creation of the the request so setting the `CookieJar` while creating the request is not an option. Concrete use case: https://github.com/paslandau/guzzle-rotating-proxy-subscriber  (setting up the request in [RotatingIdentityProxy](https://github.com/paslandau/guzzle-rotating-proxy-subscriber/blob/master/src/Proxy/RotatingIdentityProxy.php)).

**Comment by mtdowling** [comment]
Because cookies are handled through composition with the event system, there isn't a good way to extract a cookie jar from a request. If you really need that behavior, then I think what you have here works.

> Please note that I do not have no control over the creation of the the request so setting the CookieJar while creating the request is not an option.

Unfortunately, this would be the best option. I think the best way to handle this case would be to inject a CookieJar into a subscriber and hold on to a reference to the CookieJar.

I'm open to suggestions on this. Maybe there could be a helper method to filter out the listeners of an emitter (e.g., ``$emitter = $emitter->filter(function ($eventName, $listener) { /** return true/false */ });``).

**Comment by paslandau** [comment]
I don't quite understand what the `$emitter->filter(...)` is supposed to do in your example. Imho it really comes down to "detach any attached cookie subscribers" and "set the desired cookie subscriber" (or simply replace the `CookieJar`?). Alas I don't think thats a good way to "interface" cookie handling in a request. As a user of guzzle, I would really just  like to ask a request for it's cookie jar and replace it if needed :)

I understand that due to the way cookie handling is implemented, there's probably no easy way to provide a clearer interface, because it's handed of to a subscriber. That elegantly decouples cookie handling and is more a less an "extension" of the request instead of a core property [like the URL for instance]. But it also makes working with cookies a little harder  (same holds true for redirects and the `Redirect` subscriber, btw).

I guess my ideal solution looks like `RequestInterface::getCookieJar` and `RequestInterface::setCookieJar`. If cookies are disabled, `getCookieJar` returns `null` and if `null` is passed to `setCookieJar`, cookie handling is deactivated (any possible subscriber is detached). Further, if cookie handling was disabled on request instantiation, it will be enabled if a `CookieJar`is passed to `setCookieJar`.

Please note that this comes purely from an "end user [of guzzle]" perspektive so I might have missed some implications here.

**Comment by mtdowling** [comment]
> I don't quite understand what the $emitter->filter(...) is supposed to do in your example.

It basically would be a function that filters the listeners. Just like PHP's array_filter, but it would receive the name of the event and function, and return try/false to remove from a clone of the emitter.

> I guess my ideal solution looks like RequestInterface::getCookieJar and RequestInterface::setCookieJar.

I don't think this is going to happen simply because cookies are not owned by a request, they're composed with the request. I don't want to add this to Guzzle 5 because it would be an incompatible feature with Guzzle 6 which will use PSR-7.

I think the best option for now is to just filter out the event listeners as you've been doing-- it works, it doesn't require changes in Guzzle, and doesn't couple messages to cookies.
