### ISSUE TITLE
Serializing Guzzle

### ISSUE THREAD

**Issue by nodeworks** [guzzle/guzzle#1078]
Hi,

I think I may have a unique case but nonetheless I thought I'd post it. the Issue is with using Guzzle with Drupal 7. I have a form that i've made into a class, that class gets Guzzle feeded to it through the constructor and saved to a property of the class. The form gets cached automatically by Drupal core and it has to serialize this to accomplish that. It runs into an "Cannot serialize a Closure..." error when trying to serialize the RequestFsm handler which contains closures. Is there anyway around this or is it an issue I am going to have to work out outside of Guzzle?

**Comment by mtdowling** [comment]
Yeah, you can't serialize a Guzzle client because it uses closures. I think you'll need to find a workaround for this in your application. I'm not sure what Guzzle could do to make this work. Maybe subclass the client you're serializing and add the necessary serialization functions on your child class to allow serialization?
