### ISSUE TITLE
[v6] No method is configured to handle the form_params config key

### ISSUE THREAD

**Issue by ignasbernotas** [guzzle/guzzle#1115]
I'm trying to send a simple POST request, but this exception gets thrown:
```
InvalidArgumentException in MessageFactory.php line 185:
No method is configured to handle the form_params config key
```
My code:
```php
$client = new \GuzzleHttp\Client();
$client->setDefaultOption('verify', false);
$response = $client->post(config('api.url'), [
    'form_params' =>  [
        'credential_0' => 'xxx',
        'credential_1' => 'xxx'
    ]
]);
```

**Comment by mtdowling** [comment]
Looks like you're using v5.

**Comment by sameg14** [comment]
Why did you guys change this from ```body``` to ```form_params```? Now for every repo I have to go in and do a find-replace when moving from 5 to 6!

**Comment by mtdowling** [comment]
Sorry. It's a major version bump so it's expected you'll need to make changes to upgrade. body allowing an array is ambiguous as to how you want the POST body formatted.

**Comment by sameg14** [comment]
If the value of body is a string then its raw data, if its an array, then its key value pair data. Would you happen to have the link to the PR where this was introduced? I would really like to look into why this was changed. 
Just because you use semantic versioning correctly, doesn't mean that the code shouldn't be backward compatible for a feature that is likely to cause a very large percentage of users to have to go in and do a find and replace for no good reason and no added benefit!

**Comment by kamilsk** [comment]
Hi! Please read the documentation before upgrading major version. https://github.com/guzzle/guzzle/blob/master/UPGRADING.md

> The body option no longer accepts an array to send POST requests. Please use multipart or form_params instead.

**Comment by wazirsoft** [comment]
Got this same problem but as I am using v4 ```form_params``` is ```body```
like this 

```
$res = $client->post('https://example.com', [
            'headers' => [
                'User-Agent' => 'Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.2 (KHTML, like Gecko) Chrome/5.0.342.3 Safari/533.2',
                'Accept'     => 'application/json',
                'X-API-TOKEN' => ['whatever__you+want_to_send']
            ],
            'body' => [
            	'example_name' => 'example_value',
            ]
        ]);
```
