### ISSUE TITLE
Is there a way to access Response::getEffectiveUrl or Transaction::getTransferInfo ?

### ISSUE THREAD

**Issue by Briareos** [guzzle/guzzle#1130]
I know I can implement `Response::getEffectiveUrl` easily in middleware, but I still have to ask is there a plan to support those, since `curl_getinfo` is pretty deep in `CurlMultiHandler`, and I'd rather avoid copying the entire class only to add cURL transfer info somewhere. Currently, it's only present in rejection exception.

**Comment by mtdowling** [comment]
Because curl is not used for redirects, I don't know if getting the effective URI from curl will be that valuable. It would really come from the redirect middleware. You could use a history or tap middleware in order to intercept each request before it is sent.

There was a related issue opened here, which includes a workaround for accessing curl information: https://github.com/guzzle/guzzle/issues/1091. I am still open to adding a new request option to emit this information in a callback.

**Comment by Briareos** [comment]
I actually somehow missed the `handle_factory` option.

>I am still open to adding a new request option to emit this information in a callback.

I think I will implement something like that in a custom `CurlFactory` until then; kinda like `sink`, but for transfer info. Would definitely like to see it implemented in core, since it holds some valuable low-level info.

**Comment by dume2007** [comment]
You can find answer at Duplicate of #1091
