### ISSUE TITLE
internal server error when using postAsync

### ISSUE THREAD

**Issue by lesfleurs** [guzzle/guzzle#1137]
I keep getting a 500 server error when trying to send concurrent requests using the postAsync methods, I have checked the log file and there is no detailed information being generated. I only know the error occurs right after i call unwrap. Any ideas?

**Comment by mtdowling** [comment]
Can you set the debug request option to true and check the output?

**Comment by lesfleurs** [comment]
All squared i was under the impression that the async method was instantaneous and i didn't realize i had to call wait()

**Comment by tylercollier** [comment]
Thanks for the tip @lesfleurs. That solved it for me too.

@mtdowling, I think the doc is unclear. On [this page](http://docs.guzzlephp.org/en/latest/quickstart.html), it doesn't mention `wait()` in the [Async requests](http://docs.guzzlephp.org/en/latest/quickstart.html#async-requests) section. It's not until the end of the [Concurrent requests](http://docs.guzzlephp.org/en/latest/quickstart.html#concurrent-requests) section that it's mentioned, and it does so like this:

```
// Force the pool of requests to complete.
$promise->wait();
```

This mislead me because it sounds like it has to do with pools, which I'm not using.

**Comment by tylercollier** [comment]
It is mentioned here: http://docs.guzzlephp.org/en/latest/faq.html
