### ISSUE TITLE
What’s the easiest way to add an optional file to a POST request?

### ISSUE THREAD

**Issue by jonnybarnes** [guzzle/guzzle#1150]
Been testing this, and my initial code looks like this:

```
<?php

require "../vendor/autoload.php";

$file = true;

$client = new \GuzzleHttp\Client();
if ($file == true) {
    $response = $client->post('https://httpbin.org/post', [
        'multipart' => [
            [
                'name' => 'h',
                'contents' => 'entry'
            ],
            [
                'name' => 'content',
                'contents' => 'A new note'
            ],
            [
                'name' => 'photo',
                'contents' => fopen('/tmp/image.png', 'r')
            ]
        ],
        'headers' => [
            'X-Foo' => 'Bar'
        ]
    ]);
} else {
    $response = $client->post('https://httpbin.org/post', [
        'form_params' => [
            'h' => 'entry',
            'content' => 'A new note'
        ],
        'headers' => [
            'X-Foo' => 'Bar'
        ]
    ]);
}
echo '<pre>' . $response->getBody() . '</pre>';
```

I’ve noticed `phpmd` complain about methods having if/else blocks saying the code can always be simplified.

A crude simplification is to just always use `multipart` regardless of if the request has any files.

**Comment by mtdowling** [comment]
Maybe there could be a helper function that returns an associative array with the relevant request options. For example, you give the function a hash of field names mapping to a string or file, and the function returns an array containing either a "multipart" or "form_params" array with the relevant options. You could then use the `+` union operator to add the POST request options to your existing request options.

```php
$formOption = form_helper(['foo' => 'bar']);
$requestOptions = ['headers' => ['X-Foo' => 'Bar']];
$requestOptions += $formOption;
// send request
```

**Comment by Shaked** [comment]
Hey guys, I am trying to think about what would be the right way to implement this 'helper'. I have thought about 3 options: 

- Adding a method that returns an array in [RequestOptions.php](https://github.com/guzzle/guzzle/blob/master/src/RequestOptions.php)
- Creating a new `Payload` class that has a static method `format` e.g `Payload::format([['foo' => 'bar']);` and returns the relevant hash. Having said that, it might be nicer to pass all available params via this method: `Payload::format($params, $headers)` and it will add the arrays together and return the most relevant `$requestOptions`.
- Instead of letting Guzzle to decide by checking the actual hash, we can just use a method like `addFile` which key should be used ("multipart" or "form_params") - I guess that in this case, it means that we choose the builder pattern. 

In case options 3 is not relevant, I guess that once the 'contents's' value is a resource it means that the key is "multipart". 

What do you think? 

Shaked
