### ISSUE TITLE
Setting proxy

### ISSUE THREAD

**Issue by linkinkin** [guzzle/guzzle#1156]
How can I set proxy in a easy way with that request?

$client = new Client();
$crawler = $client->request('GET', "http://www.google.com");

Thanks

**Comment by kamilsk** [comment]
http://docs.guzzlephp.org/en/latest/search.html?q=proxy&check_keywords=yes&area=default

**Comment by linkinkin** [comment]
@kamilsk Thanks for showing me how to search! I didn't know that -_-

**Comment by kamilsk** [comment]
In this case, you would have immediately found the answer to your question
```php
$client->request('GET', 'http://www.google.com', [
    'proxy' => [
        'http'  => 'tcp://localhost:8125',
        'https' => 'tcp://localhost:9124',
    ]
]);
```

**Comment by linkinkin** [comment]
No, you're wrong. Did you run this code?
I was able to do with:

$client->getClient()->setDefaultOption('config/curl/'.CURLOPT_PROXY, 'http://proxy:8080');

Then execute the request:

$crawler = $client->request('GET', 'https://www.whatismyip.com/');

It worked perfectly.

**Comment by mtdowling** [comment]
@linkinkin I think you might be using a different version of Guzzle. The path type syntax has been removed in v6. The "proxy" option should work though in v4, 5 and 6. Wither way, glad it's working now.

**Comment by kamilsk** [comment]
> Next time don't be so rude.

I was not rude.

> No, you're wrong. Did you run this code?

Yes, you are right, I had to use either this
```php
$client->createRequest('GET', 'https://www.whatismyip.com/', [
    'proxy' => 'http://proxy:8080'
]);
```
or this
```php
$client->get('https://www.whatismyip.com/', [
    'proxy' => 'http://proxy:8080'
]);
```
http://docs.guzzlephp.org/en/v5/request-options.html?highlight=proxy#proxy
http://docs.guzzlephp.org/en/v6/request-options.html?highlight=proxy#proxy

But

> It worked perfectly.

Because you showed an example from https://github.com/FriendsOfPHP/Goutte, and it's client is not Guzzle client, it's Goutte client, which inherits `Symfony\Component\BrowserKit\Client`, and has a completely different interface https://github.com/symfony/BrowserKit/blob/master/Client.php#L289
