### ISSUE TITLE
POST params with null values - wrong body generated

### ISSUE THREAD

**Issue by dopesong** [guzzle/guzzle#1181]
```curl --data "ptest=&fields" http://localhost/test.php```

test.php content:

```php
<?php
var_dump($_POST);
```

Response:

```
array(1) {
  ["ptest"]=>
  string(0) ""
}
```
As I mentioned in #973

It should be always with trailing = for POST

**Comment by kamilsk** [comment]
Hi, @dopesong! What behavior do you expect?

```
array(1) {
  ["ptest"]=>
  string(0) "",
  ["fields"]=>?
}
```
And as the above example refers to the Guzzle?

**Comment by dopesong** [comment]
I just wanted to show example that php $_POST not accept param from body if there is no =. For example `$params = ['foo' => null, 'bar' => '']`, so guzzle will send non valid request body: like this: `foo&bar=` instead of `foo=&bar=`

**Comment by mtdowling** [comment]
This is intentional. Some APIs utilize empty values in the query string (e.g., Amazon S3), while others require a trailing equal sign. This is a feature that allows you to use whichever one is necessary for the API you are requesting. You should cast each value to a string before passing it to Guzzle for it to always have a trailing "=".

**Comment by RallyCongressStaff** [comment]
This behavior seems like it is out of spec.  "The control names/values are listed in the order they appear in the document. The name is separated from the value by `=' and name/value pairs are separated from each other by `&'."

https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4
