### ISSUE TITLE
Fatal error curl_reset()

### ISSUE THREAD

**Issue by danelsan** [guzzle/guzzle#1184]
The server where I send the request have php 5.4 and I know that i can receive this error.
I'd like to use another handler like sockets but not curl. Can I do this? I not found anything online.
Thanks.

**Comment by jeskew** [comment]
The [StreamHandler](https://github.com/guzzle/guzzle/blob/master/src/Handler/StreamHandler.php) uses PHP streams instead of cURL. A tutorial on how to instantiate a Guzzle client with a handler can be found [in the handler & middleware documentation](http://guzzle.readthedocs.org/en/latest/handlers-and-middleware.html#handlers).

**Comment by anlutro** [comment]
If PHP 5.5 is required to use the CurlHandler, can't Guzzle automatically discard that option if the PHP version is older? That is, add a check [here](https://github.com/guzzle/guzzle/blob/6692db3cda013e8357330243c33fe1838d0ea6f5/src/functions.php#L107-L109) which prevents the CurlLoader from loading if the PHP version is less than 5.5.
