### ISSUE TITLE
Explicit Google App Engine support, especially for HTTPS requests

### ISSUE THREAD

**Issue by atrauzzi** [guzzle/guzzle#1191]
I'm currently going through some troubles getting Guzzle-based libraries working on Google App Engine.

I'm not convinced any of this is directly Guzzle's fault (obviously GAE is quite particular) - although I think there is an opportunity for Guzzle to make it through intact when running in this environment.

So far, the issues I've been encountering are related to whenever I try to access `https` URLs.  Based on my limited research, Guzzle has 3 ways of running on GAE:

 - Via cURL lite
 - [Via a custom built GAE `curl.so`](https://code.google.com/p/googleappengine/issues/detail?id=9343#c41) [(related SO question)](http://stackoverflow.com/questions/31631596/curl-error-7-during-guzzle-request-on-google-app-engine) [(related ticket)](https://code.google.com/p/googleappengine/issues/detail?id=12178)
 - Via stream wrappers which leverage Google's sockets

Reading Google's documentation and even their early explorations into implementing cURL on PHP, their preference was clearly to have people using the sockets directly.  Many people chimed in saying that this was unrealistic given the large body of work based on cURL (ahem, guzzle!).

That all said, it would appear as though if I specify `google_app_engine.enable_curl_lite = 0` (or perhaps simply even omit it) in my `php.ini`, my runtime ends up with no cURL libaries.  Thus paving the way for guzzle to [successfully check](https://github.com/guzzle/guzzle/blob/master/src/functions.php#L111) `allow_url_fopen`.
Unfortunately what I'm now running into is a problem with Guzzle expecting to find certificates.  Now, I'm not 100% certain I've got a handle on what's going on here, but perhaps it's not needed in this scenario, as per @mtdowling's [comment here](https://github.com/aws/aws-sdk-php/issues/427#issuecomment-66229548)?

PHP is now fully supported on app engine and although it has peculiarities, it's a fairly appealing PaaS solution.  It would stand to reason that Guzzle will find itself in this environment [with increasing frequency](https://code.google.com/p/googleappengine/issues/list?q=CURL+php).
To that end, it's my hope that any fix made here will be backported as far back as is reasonable to expect so that all libraries that depend on Guzzle will be able to start working with HTTPS URLs on GAE.

Thanks for reading, hopefully I've been comprehensive enough! ;)

**Comment by mtdowling** [comment]
> Explicit Google App Engine support, especially for HTTPS requests

IMO, this implies that Guzzle is automatically tested on GAE. I'm happy to take PR's and suggestions about GAE support, but I don't want to commit Guzzle to 100% working on GAE until they add better client support that is compatible with what PHP offers.

Is Guzzle via cURL working with GAE now that #1164 is addressed?

> Unfortunately what I'm now running into is a problem with Guzzle expecting to find certificates

Yeah, GAE used to not support a bunch of context options. I'm not sure if they've updated since my comment in 2014 though. If they have not, then disabling SSL validation is one option. I'm not sure what the alternative would be with GAE. Did you have any ideas?

**Comment by atrauzzi** [comment]
@mtdowling - Take a look at [this ticket I opened](https://code.google.com/p/googleappengine/issues/detail?id=12178), and let me know what you think. From what I can tell, this should hopefully resolve issues with cURL and HTTPS on GAE.

There might however be a remaining scenario which perhaps you can help me better understand:  If someone elects to use stream wrappers (who are we to judge), are the certificates still required?  If the answer is _no_, then currently, Guzzle might still be enforcing the presence of certificates when using stream wrappers and electing to display the [missing certificates exception](https://github.com/guzzle/guzzle/blob/e63c583a936fa7304eab02aa7826d8df157d3330/src/functions.php#L192).

As far as google's client support, I know that they allow for the enabling of a `curl.so` module (as of February 2015)[http://code.google.com/p/googleappengine/issues/detail?id=9343#c41].  Would you consider that sufficient, or are there things within their implementation still missing?

**Comment by mtdowling** [comment]
> Take a look at this ticket I opened, and let me know what you think. From what I can tell, this should hopefully resolve issues with cURL and HTTPS on GAE.

Yeah, that ticket would solve the issue in Guzzle.

> If someone elects to use stream wrappers (who are we to judge), are the certificates still required?

For normal PHP: yes. For GAE, I don't think it is. They don't even support using a cert AFAIK. See: https://cloud.google.com/appengine/docs/php/urlfetch/#PHP_Secure_connections_and_HTTPS

>> All other values of ssl contexts options are ignored.

Their cURL implementation seems equally crippled: it doesn't even support curl_multi. I'm starting to shy away from promising any sort of GAE compatibility. Honestly I think GAE should strive to be compatible with the rest of the PHP community, including Guzzle.

**Comment by atrauzzi** [comment]
@mtdowling - Keep in mind, there are two implementations of cURL on app engine now.  "cURL lite" and then an actual `curl.so`.  Are you saying both of them don't support `curl_multi`?  [This page](https://cloud.google.com/appengine/docs/php/) would seem to indicate that it's only the lite version that doesn't support it.  Which really, I don't see many people electing to use anymore.

Beyond that, I believe google will be making the certificate available at a standard Debian/Ubuntu style location, so that's at least moving through the system.  I'm in total agreement that they should play nicely with the existing tools and community, it just requires some advocacy I'd say.

All that said, it would still be nice to have guzzle make a best effort to try and detect when it's on GAE and not try to set the certificate during stream requests.

Based on the two things above (one of which I've already done the legwork on), promising GAE compatibility doesn't seem *that* unreasonable.  We're one if-statement away.

**Comment by mtdowling** [comment]
> This page would seem to indicate that it's only the lite version that doesn't support it. Which really, I don't see many people electing to use anymore.

Good to know. Did they implement their own version of cURL?

>> The cURL extension uses the Sockets service and is subject to the Socket service's quotas and restrictions.

> Beyond that, I believe google will be making the certificate available at a standard Debian/Ubuntu style location, so that's at least moving through the system

Placing a file there might help, but they would still need to allow clients to use custom CA bundles, right? If they just ignore custom CA bundles, then they are excluding users who are using custom bundles.

> All that said, it would still be nice to have guzzle make a best effort to try and detect when it's on GAE and not try to set the certificate during stream wrapper requests.

Note that if GAE supports PHP 5.6, then this becomes a non-issue because Guzzle will no longer try to find a CA bundle on disk.

As long as it's as simple if statement and not too hacky, I'm open to suggestions on how to do what you're saying.

> promising GAE compatibility doesn't seem that unreasonable

Possibly, but with a number of caveats. All that said, I don't want to make any promises for something that is not free to automate tests for (e.g., Travis). But we can try to make it work at least.

**Comment by atrauzzi** [comment]
I'm not sure what the story is for custom CA bundles unfortunately.  If you're interested, feel free to jump in on that ticket with questions.  Also, you can use GAE free without supplying billing information, they only start to charge you when you require storage or VMs.

The _if_ statement I'm thinking of would be to just detect if specific GAE classes exist.  There's a Google App Engine support library for Laravel 5 that has a [nice example](https://github.com/shpasser/GaeSupportL5/blob/master/src/Shpasser/GaeSupportL5/Foundation/Application.php#L121) where it does this.

Then you'd just have to combine that with whether you were using guzzle with stream wrapper support and sidestep loading any certificates.

**Comment by atrauzzi** [comment]
@mtdowling - I got [an answer](http://stackoverflow.com/questions/31631596/curl-error-7-during-guzzle-request-on-google-app-engine#comment51770582_31631596) from someone at Google regarding the correct location for their cert bundle on GAE.

`/etc/ca-certificates.crt`

You can look for this file along with the other various sources for now.  Eventually they're going to also implement the Debian default, but this would be nice to have now so that my app can start working soonish? :)

**Comment by codemonkeynorth** [comment]
I am trying to use this firebase sdk Google App Engine which uses google client 2.0 / guzzle 6.0 on 
https://github.com/kreait/firebase-php/tree/1.x

currently it's crashing Google Cloud SDK environment's php (5.5.26) on this line
https://github.com/guzzle/guzzle/blob/113071af3b2b9eb96b05dab05472cbaed64a3df4/src/Handler/StreamHandler.php#L312

`$resource = fopen((string) $request->getUri()->withFragment(''), 'r', null, $context);`

does anyone know why this would crash php?
`ERROR:root:php failure (-1073740791)

I'm on Windows and i placed my cert at in c:\Windows\curl-ca-bundle.crt in order to allow guzzle's https calls to work (which I got from here https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt .. not sure if it is the right one)

I realise I'm using several libraries here, but again it's the fopen line in guzzle that's crashing the php, so that would be my first place to consider

thanks for any advice
J
