### ISSUE TITLE
Client magic methods break IDE autocompletion

### ISSUE THREAD

**Issue by slavafomin** [guzzle/guzzle#1235]
Hello!

Consider this code:

```php
<?php

namespace MyApp;

use GuzzleHttp\ClientInterface;


class ApiHandler
{
    /**
     * @var ClientInterface
     */
    protected $httpClient;


    /**
     * @param ClientInterface $httpClient
     */
    public function __construct(ClientInterface $httpClient)
    {
        $this->httpClient = $httpClient;
    }

    public function foo($data)
    {
        $response = $this->httpClient->post('foo');
    }
}
```

In the example above IDE has no idea what is the `post()` method and what is the type of the `$response` object. This really complicates my work, cause I need to manually introduce ad-hoc type annotations everywhere.

Maybe we should add those methods to the interface statically?

Thanks!

**Comment by mtdowling** [comment]
Those methods won't be added to the ClientInterface, but I'd be happy if you added them to Client. I also recommend that you use the request and send methods instead of relying on these methods.

**Comment by imanghafoori1** [comment]
This is a none issue and could be easily solved by php docblocks.
see the link below : 

http://stackoverflow.com/questions/15634021/how-to-document-magic-call-and-callstatic-methods-for-ides

http://www.phpdoc.org/docs/latest/references/phpdoc/tags/method.html#examples

**Comment by slavafomin** [comment]
@imanghafoori1 that's a nice solution, thank you. Will keep it in mind ; )

**Comment by imanghafoori1** [comment]
Happy to help you that.
I am currently working on core Laravel Framewok files to provide IDE auto-completion.
It also worked very well for laravel-form-builder package.

**Comment by xbugster** [comment]
why you define the variable as ClientInterface in docblock? Just set it to GuzzleHttp\Client to highlight all available method.

**Comment by rpkamp** [comment]
I've been wondering the same thing and I have some concerns about this.

@mtdowling Why won't these methods be added to the interface? What was the intent of the interface? Was it ever intended to be used in user land or is an internal thing?

@imanghafoori1 that does indeed solve the IDE problem but not the deeper problem that lies underneath.
The idea behind interfaces is that you can type hint for them and then pass any class that implements that interface to the method that hints for it. This also means that you must _not_ call any method on the object you got passed that is not defined on the interface because it _breaks the contract_!
As soon as you call methods that are not defined in the interface the type hint is completely useless because the code doesn't follow the contract defined in said type hint.

**Comment by mtdowling** [comment]
> Why won't these methods be added to the interface?

The most important reason is that it would be a breaking change for anyone whose implemented the interface.

I recommend using the `request` method and not coupling with the concrete Client class.

**Comment by imanghafoori1** [comment]
The whole idea behind interfaces in any programming language is to aid
programmers as human beings.

Some modern languages like python do not have anything like interfaces at
all.
And It is proven that large and enterprise applications are possible to
build without any problem because of lacking "interfaces".
So do not get heavily concerned with them.
در تاریخ ۱۹ آوریل ۲۰۱۶ ۲:۱۷ قبل‌ازظهر، "Michael Dowling" <
notifications@github.com> نوشت:
