### ISSUE TITLE
Getting the built URL

### ISSUE THREAD

**Issue by carlb-jomedia** [guzzle/guzzle#1273]
Hi,

I have a question, I've tried for a week now to have guzzle build a URL and then access this url, but I can't make it work. I understand that it's not the purpose of guzzle, but since I use it for everything else in the project, I would like to use it for this call too. So the use case is that we need to build a URL to return to the front end for streaming purpose. Since we don't stream directly and use a provider, we need to build the URL, but let the frontend make the call. 

Do you think that would be possible with Guzzle?

**Comment by mtdowling** [comment]
The URI functionality of Guzzle is available in the guzzlehttp/psr7 package in the Uri.php file: https://github.com/guzzle/psr7/blob/master/src/Uri.php. Using this file, you will be able to build up a URI that can be cast to a string.

**Comment by christhomas** [comment]
Hi, 

your answer doesn't address the initial question, which is, now that guzzle has all the options, headers, etc setup for a request, how can you request that url to be given back to you through an API call.

it's a fairly common api method to find on these types of libraries.

everybody of course knows you can manually build the url as you request, but that's not the same as obtaining the url that guzzle is using, how can I prove the url is built in the same way, if I cannot access it

what the OP is requesting, is something like $client->getUrl / getUri / similar function name.

It appears a basic function that guzzle should probably already provide, otherwise how do you test that guzzle is building the URI in the requested way if guzzle itself doesn't have a function to return this value?  Surely there are unit tests for this, therefore, there must be a way to obtain the final uri to make sure the final uri is constructed properly.

so if there is a way to do this already, do you know the answer and can help us out by providing it?

Thanks!

**Comment by rvanlaak** [comment]
In our use case a service class needs to return the URL where the user has to get redirected to, instead of performing the GET request.

Configuration of the client (`base_uri`, basic get-parameter authentication) nicely happens outside of that service class, as the service class should not be aware of that.
