### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by eskrano** [guzzle/guzzle#1319]
https://github.com/guzzle/guzzle/blob/master/src/Cookie/CookieJar.php#L89

This function or method? I do not understand

**Comment by LukeNZ** [comment]
+1. Guzzle's Cookie implementation is extremely undiscoverable and the documentation on it is fractured and poor. 

I can't even set a damn cookie to pass on to another request.

**Comment by mtdowling** [comment]
> This function or method? I do not understand

It's a static method on the class. You don't need to worry about it unless you're implementing a custom CookieJar.

> +1. Guzzle's Cookie implementation is extremely undiscoverable and the documentation on it is fractured and poor.

The point you're making is not related to the issue as reported. It sounds like you're asking how to add cookies to a request, which is not related to whether or not a method is static.

If you want to maintain state between cookies, then you need to use the `cookies` request option.

```php
// Persist cookies across all requests
$jar = new \GuzzleHttp\Cookie\CookieJar();
$client = new GuzzleHttp\Client(['cookies' => $jar]);
$client->request('GET', '/get');
```

If you want to add ad-hoc cookies to a request, then you need to set a header on a request:

```php
// Add ad-hoc cookies
$response = $client->request('GET', '/', ['headers' => 'Cookie: foo=bar; baz=bam']);
```

**Comment by LukeNZ** [comment]
Maybe then you can help me then, mtdowling. My past 3 hours have resulted in nothing but frustration.

I am interacting with an API that on authentication, responds with a cookie (or set of cookies, I haven't yet worked that out yet).

To perform any further request with this API, I need to resend that cookie I was provided with back to them. 

What I have so far:

### Construct

        $this->jar = new CookieJar();
        $this->client = new Client([
            'cookies' => $this->jar
        ]);

### Authenticate

        const SPACE_TRACK_URL = 'https://space-track.org';

        $response = $this->client->post(Ephemeris::SPACE_TRACK_URL . '/ajaxauth/login', [
            'form_params' => [
                'identity' => $this->identity,
                'password' => $this->password
            ]
        ]);
        $this->jar = CookieJar::fromArray($response->getHeaders()['Set-Cookie'], Ephemeris::SPACE_TRACK_URL);


### Perform actual requests

        $response =  $this->client->request('GET', Ephemeris::SPACE_TRACK_URL . $url);
        return $response;

Attempting to perform an actual request results in a 401 unauthorized error, presumably because I haven't sent any (or just malformed) cookies through. 

Is there anything I'm doing wrong on the setup side here?
