### ISSUE TITLE
Using different options on Requests in Guzzle\Pool

### ISSUE THREAD

**Issue by teemule11** [guzzle/guzzle#1332]
Hi,
I am currently working on the following problem: I want issue multiple concurrent Requests using different request options with the client; right now, when using Guzzle\Pool, I have to pass in the request options on creation of the Guzzle\Pool object, since it creates just one client instance. So, if I want to set different timeouts on the requests in the Pool, this would not be possible. But what would be the preferred way to achieve this, or am I overlooking something here?

**Comment by mtdowling** [comment]
The pool supports options that can be applied to each request: https://github.com/guzzle/guzzle/blob/master/src/Pool.php#L28

When sending requests through a pool, instead of yielding requests, you can also yield out callback functions. These callback functions are then invoked with the options of the Pool and can be used to create requests dynamically based on the Pool configuration. Here's an example https://github.com/guzzle/guzzle/blob/master/tests/PoolTest.php#L75
