### ISSUE TITLE
Infinite loop, when HTTP Connection breaks

### ISSUE THREAD

**Issue by hgiesenow** [guzzle/guzzle#1355]
Using Guzzle 5.2.0 with cURL 7.19.7 and HTTPS PUT

Under some rare conditions (when Server unexpectedly closes the connect) the whole script hangs forever (aborted it after 10 days of doing nothing than consuming cpu).
I have a strong suspicion that it's the while-loop in send() in Client.php. Sadly it's almost impossible to debug this behaviour, especially in a static context. The abort condition for the loop is very obfuscated, i hope it has been refactored in 6.x

The Network Connection for the Script was in the state CLOSE_WAIT all the time.

**Comment by castarco** [comment]
I've found a bug in other project (PHP-VCR), probably not related with this one, but that is causing an infinite loop inside Guzzle: https://github.com/php-vcr/php-vcr/issues/155 .

The infinite loop caused by the other bug is inside CurlMultiHandler::execute , maybe the same problematic loop?

**Comment by mc0** [comment]
We've had this same issue at SharpSpring via a lib that uses Guzzle. The underlying issue (as far as I can tell) is from this line that has no timeout:
```
while (curl_multi_exec($this->_mh, $this->active) === CURLM_CALL_MULTI_PERFORM);
```

That seems like it should have some sort of timeout. I'll update this issue if we can run strace/gdb on the processes.

**Comment by TysonAndre** [comment]
I'd suggest adding a usleep in that loop instead of immediately calling it again, to avoid 100% cpu usage. (Possibly in addition to whatever timeout you planned)

`while (curl_multi_exec($this->_mh, $this->active) === CURLM_CALL_MULTI_PERFORM) { usleep(250); }`

https://github.com/adsr/phpspy is of help in debugging issues like this.

Note that newer versions of libcurl removed MULTI_PERFORM as a result code, because it was almost always misused.

**Comment by csimpi** [comment]
This has never closed, solved? I'm having the same problem.

**Comment by GrahamCampbell** [comment]
Please refrain from replying to issues with "same". Please subscribe to the issue if you are interested in it, or better still, suggest a fix via a PR.
