### ISSUE TITLE
using GuzzleHttp\Pool doesn't free up memory after request is fulfilled

### ISSUE THREAD

**Issue by drsect0r** [guzzle/guzzle#1407]
I need to download a lot of remote packages. I am using the Pool function according to the documentation here: http://docs.guzzlephp.org/en/latest/quickstart.html#making-a-request

I'm not sure how I can free up the used memory. The packages are all small but several tens of thousands. How can I properly unset/free $response? unset(), $response->getBody()->close(); all seem not to do what I want. 

``` php

use GuzzleHttp\Pool;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;

require __DIR__ . '/vendor/autoload.php';

$client = new Client(['base_uri' => '...']);

$requests = function ()
{
    ...

    yield $index => new Request('GET', ...);
};

$pool = new Pool($client, $requests(), [
    'concurrency' => 50,
    'fulfilled' => function ($response, $index)
    {
        $content = $response->getBody()
                            ->getContents();

        file_put_contents('storage/' . $index, $content);

        print 'fulfilled index:' . $index . PHP_EOL;
    },
    'rejected' => function ($reason, $index)
    {
        print 'rejected index:' . $index . PHP_EOL;
    },
]);

$promise = $pool->promise();

$promise->wait();
```

**Comment by mtdowling** [comment]
Can you ensure that garbage collection is enabled? Perhaps in your iterator, you can call `gc_collect_cycles()`.

**Comment by drsect0r** [comment]
@mtdowling Thanks for the suggestion! however, I don't see any noticeable drop in memory usage. I call gc_collect_cycles() after a request has finished.

**Comment by mtdowling** [comment]
Hm, in that case we'll need more info. Can you provide a complete reproducible code same, PHP version, and curl version?

**Comment by mtdowling** [comment]
I was unable to reproduce this behavior on PHP 7.0.3. Here's an example I put together to try to reproduce (first run `make start-server` from a guzzle git checkout):

```php
<?php

require 'vendor/autoload.php';

use GuzzleHttp\Pool;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\Tests\Server;

$client = new Client();
$perfUrl = Server::$url . 'guzzle-server/perf';
echo $perfUrl . "\n";

$requests = function () use ($perfUrl) {
    for ($i = 0; $i < 10000; $i++) {
        yield $i => new Request('GET', $perfUrl);
    }
};

$t = microtime(true);

$pool = new Pool($client, $requests(), [
    'concurrency' => 50,
    'fulfilled' => function ($response, $index) {
        $content = $response->getBody()->getContents();
        file_put_contents('/tmp/guzzle-test-' . $index, $content);
        echo memory_get_usage(true) . "\n";
    },
    'rejected' => function ($reason, $index) {
        print 'rejected index:' . $index . PHP_EOL;
    },
]);

$promise = $pool->promise();
$promise->wait();

echo (microtime(true) - $t) . "\n";
echo memory_get_usage(true) . "\n";
```

If you run the above code example, you'll see the memory footprint remain constant.

1. When you say that the pool does not free up memory, how much memory are you talking about?
2. Does the amount of memory rise with each iteration, or does it remain constant?
3. In your generator example, you have a placeholder `...`. What's the actual code that was omitted?
4. Can you provide suggestions on how I can edit my code example to reproduce the error you are describing?

**Comment by drsect0r** [comment]
@mtdowling 

1. The familiar `Allowed memory size of ... bytes exhausted (tried to allocate ... bytes)` Current memory_limit is set to 1GB, I can see in htop that memory climbs rapidly.
2. It remains constant for anywhere between 2 and 35 iterations
3. Parsing about 100k JSON files, conduct sanity checks and yield request based JSON data. 
4. I'm not sure, I have the impression that my code consumes more memory when more packages are being downloaded. After a request is finished is the request destroyed? 

At the moment, I'm unable to provide with a code example. I did put `memory_get_usage()` in my current code with the following results. If you agree, I can give you access to the code directly?
``` 
php -q test.php
4194304
...
6291456
...
8388608
...
10485760
...
12582912
...
14680064
...
16777216
...
18874368
...
20971520
...
23068672
...
25165824
...
27262976
```

```
cat output.txt | uniq -c
      1 4194304
      3 6291456
      3 8388608
      6 10485760
      2 12582912
      9 14680064
      9 16777216
     21 18874368
      6 20971520
     32 23068672
     16 25165824
     35 27262976
```

**Comment by mtdowling** [comment]
Interesting. I'll need a reproducible example in order to investigate this further.

**Comment by vallieres** [comment]
I too have a similar problem. I'm using Guzzle to loop through a product inventory (between 100 and 20,000 items) and API calls (limit 100 at a time). I only do GET requests, quickly take the response as string, parse it and dump it in a file. However, the peak memory usage keeps increasing. 

I also tried using request sink (in case the php://temp was saving the quest in memory), but the total memory used easily gets in the 25MB just after 2-3 calls. Tried to run the script with 20,000 items and it passed 540MB of memory.

Is there a way to release resources used by the client after a successful GET requests?

**Comment by mtdowling** [comment]
What version of cURL are you using? Perhaps you're affected by the same cURL memory leak as this user: https://github.com/aws/aws-sdk-php/issues/957#issuecomment-208765818

**Comment by vallieres** [comment]
PHP 5.6.20
curl 7.43.0

I do not seem to have the same version.

**Comment by drsect0r** [comment]
Curl 7.43.0 
PHP 7.0.5

I also don't have the same version to the post but I do have the same version to @vallieres.

**Comment by keltik85** [comment]
I also have the same problem.

I initialize the requests iterator like this (in total it should 'yield' 40000+ Request objects, but it stops at aproximately 8000):

```
$requests = function () {
        $result = $this->my_database->get_some_result ();
        $start_time = microtime ( true );
        $counter = 0;
        $result_num_rows = $result->num_rows;

        while ( $row = $result->fetch_object () ) {
            $counter ++;
            if ($counter % 25 == 0) {
                $elapsed_time = microtime ( true ) - $startTime;
                echo "Memory used after '" . $counter . "' requests:" .
                         (memory_get_usage () * 0.000001) . "MB, aproximated runtime:" .
                         (((($result_num_rows / $counter) * $elapsed_time) / 60) / 60) . "\n";
            }
            //echo "A Request was inited for id = " . $row->id . "\n";
            yield new Request ( 'GET', $some_url . $row->id );
        }
    };
```
And the pool like this:

```
$pool = new Pool ( $client, $requests (),
               [ 'concurrency' => 50,
                       'fulfilled' => function ($response, $index) {
                        //do nothing
                       },
                       'rejected' => function ($reason, $index) {
                           //do nothing
                       }
               ] );

       // Initiate the transfers and create a promise
       $promise = $pool->promise ();

       // Force the pool of requests to complete.
       $promise->wait ();

```

**Comment by PMassoels** [comment]
I seem to have the same problem. On every call I make the memory increases. The problem is that my scripts extracts 20.000 values from an excel file and uploads them with the api. In the end everything is very slow because every cycle adds 0.15 mb.

**Comment by istrof** [comment]
Hey guys, I was experiencing the same issue. Every guzzle request was adding 0.07 - 0.2 MB, so 10K requests were causing memory crash.

Then I realized that Guzzle was dev mode because Symfony commands are working in dev mode by default.
Adding "--env=prod" to the command line reduced 1GB of consumed memory down to 50MB :)

**Comment by keltik85** [comment]
> Adding "--env=prod" to the command line reduced 1GB of consumed memory down to 50MB :)

If its not in the docs or wiki or readme it should be.

**Comment by vallieres** [comment]
@keltik85 any way to set the env when simply running it as PHP script triggered from a webpage? I do not use Symfony.

**Comment by alexeyshockov** [comment]
@vallieres, different environments is a Symfony's feature, doesn't apply on "pure" PHP. You can check your framework, BTW, many have such concept now (Laravel, Yii,..).

**Comment by pablolemosassis** [comment]
Also same problem here. CPU going crazy when making lots of calls.
@alekseykuleshov we understand that environments are a framework feature, but how can we directly set Guzzle to production mode? There is no reference at all to "dev mode" in Guzzle docs.

**Comment by bong0** [comment]
I think the **needs-more-information** tag is obsolete currently, isn't it?

**Comment by kgrosvenor** [comment]
I think i get a memory leak like this when repeating the same call from my client

**Comment by celloman** [comment]
So... how does one actually get Guzzle into this mystical 'dev mode' to prevent the memory leak? We are seeing the same .15 MB leak/call... not great when dealing with large numbers of requests...

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by mtdowling** [comment]
Just wanted to quickly mention that Guzzle has no "dev" or "prod" mode. That sounds like something that is specific to Symfony or some other framework.

**Comment by ekojs** [comment]
I have same problem here, if i use the script in singleton format. The request eventually exhausts available memory. I need to parse data from response to match the parameters.

Please take look at this https://gist.github.com/ekojs/e112a89aaf1c342d3f06115b9e14a534

**Comment by Maniumn** [comment]
The problem is still exist.
I use the Guzzle 6 with Symfony 4 to make requests to an API and see the curious behavior in memory usage. What I do: typically JSON transfers from and to an API and do not store any data in the memory. 
Here you can the screenshot of the memory usage of many serial + concurrent requests: [memory usage](https://imgur.com/a/23ELFCj).
The numbers growths rapidly up to limit after you upload some files (every file stay completely in the memory. WTH?) .
'--env prod' does not help, 'each_limit()' does not support the concurrent requests and also stores data in the memory.
Here is reproduceable code of API and Guzzle based on Symfony 4: [Simple Symfony API](https://github.com/Maniumn/simple_symfony_api), [Simple Symfony + Guzzle](https://github.com/Maniumn/simple_symfony_guzzle)

**Comment by Maniumn** [comment]
Yea, cool, after **update on eightpoints/guzzle-bundle 7.4** in my main project the problem is gone *facepalm*.
In my post above with the simple example I have changed the APP_ENV to the prod only. This brought the code to the constant memory usage.

**Comment by vbarbarosh** [comment]
I faced with this issue using Google Appengine: [`\GuzzleHttp\Client()` + `\GuzzleHttp\Promise\EachPromise` consumes too much memory](https://github.com/GoogleCloudPlatform/php-docker/issues/468)

**Comment by Stalinko** [comment]
The issue still exists.
I use guzzle 6.3 with vanilla php code, I do simple get/post requests in a loop, one after another, and the memory usage constantly grows. Ubuntu 16.04.

**Comment by igorpopryadukhin** [comment]
Подтверждаю, действительно жрёт память в цикле. Даже если unset основного объекта выполнить. Это печаль (((

**Comment by Tobion** [comment]
It seems the memory leak cannot be reproduced using guzzle standalone it seems. People have mentioned using the prod env solved the problem. But Guzzle  itself does not have different environments like prod. So the problem must come from a bundle that you are using. What I've seen most people mention is https://github.com/8p/EightPointsGuzzleBundle
It's collecting data for debugging which will obviously fill memory at some point. See also https://github.com/8p/EightPointsGuzzleBundle/issues/255

So the problem should be reported there or you need to disable collecting of data. Nothing to do in Guzzle itself IMO.

**Comment by dol** [comment]
To add more clarification to this issue. From what I was able to debug in our setup. We use Guzzle to perform more than 1000 request per second to multiple upstream server. We recently experienced a massive memory leak within PHP and a corresponding CPU peak. We were able to downtrack to issue to the usage of `cURL multi handle`. Because Guzzle is very widespread and the default HTTP handler chosen by Guzzle is [CurlMultiHandler](https://github.com/guzzle/guzzle/blob/ca2892a8c2778c1821899fd2c79932e3b895f2ad/src/functions.php#L111) this problem looks like it Guzzle related.
We where able to resolve the issue by choosing the dedicated StreamHandler. To avoid curl in any way we disabled curl_init, curl_multi_init and curl_exec by adding this functions to php.ini `disable_functions` directive.
Currently Guzzle assumes that curl or multi curl is the best default handler. This might be up for discussion until the memory leak in the libcurl PHP core bug is fixed.

See https://www.drupal.org/project/drupal/issues/2595927 for a similar conclusion.

**Comment by Tobion** [comment]
@dol did you create a bug report for the php curl extension? Please reference it here.

**Comment by dol** [comment]
@Tobion There are plenty of them already reported. https://www.google.com/search?q=site%3Abugs.php.net%20curl%20memory%20leak

**Comment by Tobion** [comment]
There are only 2 open ones:
- https://bugs.php.net/bug.php?id=76484 which cannot be reproduced apparently
- https://bugs.php.net/bug.php?id=76346 which is the same as the other one

So without more information from others, nothing will happen probably as it might depend on the libcurl or openssl version.

**Comment by Hesoyam144** [comment]
The Client Works with HTTP 1.1.
Try to use the Client with HTTP 1.0

$client = new Client(['version' => 1.0]);

Works fine in my case.

Solution is here:
https://gitmemory.com/issue/guzzle/guzzle/2555/576424858

**Comment by codemistake** [comment]
I have same problem ( PHP 7.3.20 or PHP 7.4.8, Symfony, RoadRunner, curl 7.29.0 , CentOS 7, guzzle 6.5.5)
When i send any Guzzle request or just create Promise(without real send request) i have leak(many gc_status->roots, mem). The advice above(HTTP 1.0) did not work.
Has anyone found a solution?

**Comment by UnnikrishnanBhargavakurup** [comment]
I'm facing the same issue anybody got any solution for this?

**Comment by jyxjjj** [comment]
#2555 #2609 , I think it is continuing happen. 
Versions:
```bash
PHP 8.3.6
Zend Engine v4.3.6, Copyright (c) Zend Technologies
    with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
    with Zend OPcache v8.3.6, Copyright (c), by Zend Technologies
cURL Information => 8.7.1
OpenSSL Library Version => OpenSSL 3.3.0 9 Apr 2024
OpenSSL Header Version => OpenSSL 3.2.1 30 Jan 2024
```
Codes:
```php
for ($index = 1; $index <= 127; $index++) {
            $imageUrl = $images[$index];
            $imageResponse = get($imageUrl);
            if ($imageResponse['status']!==200) {
                throw new Exception("Failed to download image: $imageUrl");
            }
            $imageData = $imageResponse->body();
}
```
(get is a method call every time to new a clean guzzle instance then run get request, i am sure it is clean enough. Then it returns an array. Sorry but there was some token in it so i cannot provide these codes.)
Whatever  how `$index` larges, it always stop each (around, maybe 120-130) 126 times.
Each images are 1MB, I had released every thing I can release (I release `$imageData` every write, and didn't miss any file hwnd).

**Comment by jonnywilliamson** [comment]
> ```shell
> PHP 8.3.6
>     with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
> ```
> 

Out of interest what happens if you run the exact same loop with xdebug disabled?

**Comment by jyxjjj** [comment]
> > ```shell
> > PHP 8.3.6
> >     with Xdebug v3.3.2, Copyright (c) 2002-2024, by Derick Rethans
> > ```
> 
> Out of interest what happens if you run the exact same loop with xdebug disabled?

Nothing different. I think it didn't run in debug attached, maybe XDebug just built and loaded.
```
Allowed memory size of 134217728 bytes exhausted (tried to allocate 761856 bytes)

  at vendor/guzzlehttp/psr7/src/Stream.php:257
    253▕         }
    254▕ 
    255▕         // We can't know the size after writing anything
    256▕         $this->size = null;
  ➜ 257▕         $result = fwrite($this->stream, $string);
    258▕ 
    259▕         if ($result === false) {
    260▕             throw new \RuntimeException('Unable to write to stream');
    261▕         }
```

Btw, `        "guzzlehttp/guzzle": "^7.8.1",`

**Comment by jyxjjj** [comment]
@jonnywilliamson
Thanks for that you reminded me, after i tried to disable xdebug, i ran it on my server too.

- This time i added `memory_get_usage` and get peak usage.

  It still generating memory usage, but gc can successfully clean things after a while.

- Now i believe it is a PHP's issue and it only happen on my mac.
  (But last comment is true, not due to xdebug, due to something else like curl ext.)

Then i continuing run the same code on my mac, i found a strange thing that, it cannot be reproduced.

Different thing is:
- I put only one url to download image, download it many times.
- I added memory info count `memory_get_{peak_}usage`.

Then i tried again and again.

- The reason that i cannot reproduce is to download same image.
- If i download a list of image from array, it can be reproduced.

I thought to consider if it is a PHP curl ext's issue, but i now confused.

The code that can reproduce this issue

```
        for ($index = 1; $index <= 363; $index++) {
            $imageUrl = $images[$index];
```

The code that cannot reproduce this issue

```
        for ($index = 1; $index <= 363; $index++) {
            $imageUrl = "{ a fixed url }";
```

**Comment by stanleybenjamin** [comment]
Just incase anyone stumbles on this, please refer to this [post](https://garbers.co.za/2017/10/04/using-guzzle-for-large-request-pools/). In my case I simply use the text as soon as the request came, rather than batch up all, which could just exhaust memory quickly

**Comment by jyxjjj** [comment]
After last time i commented, i found the stream of response has a function to close.
`$response->close();`
And i also added `gc_collect_cycles`, in my case, i cannot get this issue any more.
So i will also unsubscribe this issue.
