### ISSUE TITLE
Mutex update does not fixed concurrency generator issue.

### ISSUE THREAD

**Issue by alexsup** [guzzle/guzzle#1416]
After pulling the mutex fix in promises (https://github.com/guzzle/promises/pull/20), guzzle/issues/1412 is still not fixed.

To recap...

Running the following in app/Http/routes.php (laravel on Forge & Digital Ocean):  

```
Route::get('/',function(){
    $client = new \GuzzleHttp\Client();

    $requests = function ($total) {
        $uri = 'https://api.github.com';

        for ($i = 0; $i < $total; $i++) {
            yield new \GuzzleHttp\Psr7\Request('GET', $uri);
        }
    };

    $pool = new \GuzzleHttp\Pool($client, $requests(10), [
        'concurrency' => 5,
        'fulfilled' => function ($response, $index) {
            // this is delivered each successful response
            var_dump("fulfilled");
        },
        'rejected' => function ($reason, $index) {
            // this is delivered each failed request
            var_dump("rejected");
        },
    ]);

    // Initiate the transfers and create a promise
    $promise = $pool->promise();

    // Force the pool of requests to complete.
    $promise->wait();
});
```

Causes the following error:

<img width="1007" alt="screen shot 2016-02-29 at 11 21 46" src="https://cloud.githubusercontent.com/assets/13382954/13431416/3f711f48-dfc1-11e5-9c3d-c37e282c8bfa.png">

This issue isn't triggered if I run it as scheduled command nor does it happen if I run it locally (out of the box homestead setup).

Please can you let me know if you need to any further information.

Thank you!

AB

**Comment by mtdowling** [comment]
Interesting. That looks like a different error than what the mutex was implemented to solve.

**Comment by mtdowling** [comment]
I can't reproduce this. Can you ensure that you've updated your dependencies?

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
