### ISSUE TITLE
What replaces client->setDefaultOption?

### ISSUE THREAD

**Issue by project707** [guzzle/guzzle#1419]
In our application we create a new `GuzzleHttp\Client` at a high class/service level and need to set options on that multiple places in child classes that inherit from that differently depending on what methods get called, but I can't figure out how that is supposed to be done to an instantiated client on the fly now (Guzzle 6.1.1).

I'm sure I am missing something really obvious in the docs/code since this is such a common use-case. The only method I see that seems like it should do that is `configureDefaults` which is private, and I know that  `setDefaultOption` went away.

**Comment by mtdowling** [comment]
Clients are immutable in Guzzle 6, which means that you cannot change the defaults used by a client after it's created.

Maybe instead of trying to modify a client after it's created, you could utilize factories that create clients using the default values necessary for each different type required in your application.

**Comment by project707** [comment]
From the perspective of someone needing to reuse something like dynamically generated proxy settings (and others specific to a logged in "session") for a set of requests, making clients immutable sounds like a fundamental flaw.

I get that psr7 means that request settings are immutable, but why does that carry over to client instances? Just curious.

**Comment by mtdowling** [comment]
> From the perspective of someone needing to reuse something like dynamically generated proxy settings (and others specific to a logged in "session") for a set of requests, making clients immutable sounds like a fundamental flaw.

I don't see how you can draw that conclusion from your use case. Instead of dynamically modifying a client, just dynamically create clients.

Immutability is not necessary at the client level. It is not uncommon for middleware to be created that derives values based on state at a point in time. If that state changes, then the derived value must be updated accordingly, which means you either have to increase coupling between state changes and derived values or you cannot use cached/derived values in client collaborators.

Adding support for a MutableClient or something similar is something I'd consider (e.g. a separate interface and concrete class), but I do not want to change the ClientInterface or default Client implementation.

**Comment by project707** [comment]
I see where you're coming from, but having thought we could rely on the Guzzle client to hold the "state", or maybe rather metadata, of a client for us (as it could up to this point) and having built a large modular application using it that way, you can probably understand a little frustration at that having changed so decidedly. The way things were, it required less code on our side and less of a necessity to handle the state of that metadata ourselves (i.e. no need to look at a service that holds some list of attributes given to the original client, but then for all I know, doing things this way may have also reduced the size or complexity (more likely) of the Guzzle codebase, which of course also holds great value.

Anyhow I'm very familiar with the process of having to make the kinds of decisions that change everything and inevitably get in _someone's_ way, so carry on and we'll work around it. I know there are a lot of arguments surrounding this out there, and most people do seem to be on board. Hopefully I will be soon enough as well.

**Comment by bernierayxu** [comment]
agree with @project707 , my case needs to construct requests to different external service providers.

**Comment by ishapkin** [comment]
In 6.x you must create new client.
For ex., in my service I changed headers after get access token:
`php
$response = $this->client->post(
            'token',
            [
                'form_params' => [
                    'client_id' => $clientId,
                    'client_secret' => $cientSecret,
                    'grant_type' => 'client_credentials'
                ],
            ]
        );
        $this->auth = json_decode($response->getBody()->getContents());
        $config = $this->client->getConfig();
        $config['headers']['Authorization'] = 'Bearer '.$this->auth->access_token;
        $this->client = new Client($config);
`

**Comment by victor-ponamariov** [comment]
This is very inconvenient in my opinion...

**Comment by leik-software** [comment]
> ```
> getConfig
> ```

good solution @ishapkin  but getConfig is deprecated now.

**Comment by ishapkin** [comment]
Hello, @leik-software! In 6.x version in 2019 it was worked :)

Without getConfig you can store your config in variable or property, for example:

```php

// Your default config
$defaultConfig = ['base_uri' => 'https://api.example.com'];

// Your base client
$client = new Client($defaultConfig);

// Your request with base client
$response = $client->post('token', $params);
$auth = json_decode($response->getBody()->getContents());

// Update your config var
$defaultConfig['headers']['Authorization'] = 'Bearer '.$auth->access_token;

// Create new client with updated config
$client = new Client($defaultConfig);
```
