### ISSUE TITLE
Question: How does Guzzle consume chunked responses?

### ISSUE THREAD

**Issue by manuelkiessling** [guzzle/guzzle#1438]
I'm investigating if I can use Guzzle to efficiently consume data from a server that sends its response using HTTP 1.1 chunked transfer encoding. Therefore, I'm trying to grasp how Guzzle works internally in this regard.

My server sends its responses in chunks - the body is a large JSON array consisting of many JSON objects - each object is contained within one reponse chunk, thus sending the response is memory efficient from the server's point of view.

Guzzle provides a PSR-7 compatible stream interface for responses it retrieves, but how does a chunked response relate to this stream representation?

If, for example, I repeteadly call `$body->read(100)` after setting `$body` to the reponse stream via `$body = $response->getBody()` (and `$response` is a result of `$client->get`), then my PHP code only retrieves 100 bytes on each iteration, and the memory used by PHP doesn't grow. But the response chunks aren't 100 bytes large each - actually, they differ in size. Does Guzzle download the whole response before providing the stream abstraction on it? Is the response stored on the hard drive?

It would be great if you could help me understand these details.

**Comment by mtdowling** [comment]
It depends on the adapter you're using with your client. If you use the stream adapter, then it's pull based, and you can make calls to `read()` in order to block for more content from the stream. If you use the curl adapter, then it's push based, and all data is pushed to the `sink` stream configured in the `sink` request option. You can react to those push events using callbacks from curl using a stream decorator (https://github.com/guzzle/psr7#stream-implementation), or you can use the `stream` request option to opt-in to streaming responses using the pull based approach: http://docs.guzzlephp.org/en/latest/request-options.html#stream
