### ISSUE TITLE
add requests to pool after promise

### ISSUE THREAD

**Issue by inkrement** [guzzle/guzzle#1467]
How can I add additional requests to a pool after promise is called? Would it be possible to add them in the fulfilled callback?

I found some examples (https://gist.github.com/paslandau/ce8f8c034dd7058c0bfc, https://github.com/guzzle/guzzle/issues/946#issuecomment-92018988) but they are outdated and I was not able to do it like this in Guzzle6 - new request are ignored.

**Comment by inkrement** [comment]
I created an example and found the problem. It only works if the threads of the pool are all used. So if I am using 5 threads but only 1 initial request all newly added requests will be ignored. But If I add 10 initial requests it will work: 

https://gist.github.com/inkrement/76d01ea85098d29fb299cd138f5c3393

Is there a trick or would someone have a tip how to "persuade" guzzle to keep working even if not all worker-threads are used?

**Comment by mrcasual** [comment]
I am stuck on the very same problem (in fact, even our code is similar :)).

**Comment by mtdowling** [comment]
Thanks for sharing the example. I've been playing around with it, and I too am unable to get this to work.

There could be an issue with the EachPromise abstraction, but I'm having trouble identifying where the issue is coming from: https://github.com/guzzle/promises/blob/master/src/EachPromise.php.

**Comment by TiMESPLiNTER** [comment]
I also investigated into this issue. The reason is in function `EachPromise::refillPending()`. There are two cases in which there's a problem:

**CASE 1**
If `concurrency` is *not* set all requests from the original iterator get added as pending and `refillPending` never gets called again. So if you add a request to your original iterator in one of the callbacks (`fullfilled`, `rejected`) it will be ignored because the iterator already returned `false` after iterating over all of the initial requests.

**CASE 2**
If concurrency *is* set and bigger then the initial number of requests (e.x. concurrency=5, initial requests=3) it's the same problem as described in CASE 1 because all the initial requests fit into the queue and the iterator returns `false` because it iterated over all entries.

If you lower down the `concurrency` and go under the number of initial requests the chance gets bigger that a request got added to the iterator. If you set `concurrency=1` you get a 100% chance that a later added request gets fired.

**Comment by inkrement** [comment]
@mtdowling Hi Michael, is there any progress on this issue? I want to fetch data from a API with pagination, which requires the content of one page to load the next. Thus, adding some requests while processing is required.

**Comment by alexeyshockov** [comment]
@inkrement, see my answer to [this SO question](https://stackoverflow.com/questions/42754389/guzzle-pool-wait-for-requests/43525426#43525426). If I understand correctly, you have a similar case.

**Comment by inkrement** [comment]
@alexeyshockov are u sure that it works with all php versions? In my case it does not work as expected. All the response were generated but no one was "fired". One guy mentioned in SO that it works only with specific php versions.

**Comment by alexeyshockov** [comment]
@inkrement, yes, it was not compatible with old versions (before PHP 7). Changed the code, now it works.

BTW, do you still run PHP 5.x?

**Comment by inkrement** [comment]
@alexeyshockov strange, I am using PHP 7.0. Is there anything else to consider?
