### ISSUE TITLE
Proxying via socks5 (simple ssh tunnel) doesn't work

### ISSUE THREAD

**Issue by OnkelTem** [guzzle/guzzle#1484]
I can't connect via socks5 proxy. Guzzle version = 6.1.0.
The configuration is done like this:

``` php
$http_options['proxy'] = 'tcp://127.0.0.1:12345'
```

but I get the following error:
**failed to open stream: Cannot connect to HTTPS server through proxy [file] <...>/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php**

I also tried using 'socks5' scheme, but it doesn't seem to be defined:

``` php
$http_options['proxy'] = 'tcp://127.0.0.1:12345'
```

**Unable to find the socket transport &quot;socks5&quot; - did you forget to enable it when you configured PHP?**

I also tried configuring 'curl' like this:

```
$http_options['curl'] = [CURLOPT_PROXY => 'socks5://127.0.0.1:12345'];
```

but this is just ignored by Guzzle.

So how it is supposed to be working?

I should say that making the same request via pure cURL PHP lib or `curl` command line works fine.

**Comment by mtdowling** [comment]
Are you sure that curl is installed correctly for PHP?

**Comment by OnkelTem** [comment]
Thanks for the quick reply, Michael!

I think yes. At least this snippet works fine:

```php
$ch = curl_init();
 // Simple temp service which returns your IP
$url = 'https://php-onkeltem.c9users.io/ip.php';
// Created using: ssh -f -N -D 12345 user@host
$proxy = 'socks5://127.0.0.1:12345';

curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_PROXY, $proxy);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 1);
$curl_scraped_page = curl_exec($ch);
echo $curl_scraped_page;
curl_close($ch);
```

**Comment by OnkelTem** [comment]
Any updates?

**Comment by nesttle** [comment]
Same

**Comment by nesttle** [comment]
Maybe Shared hosting CURL limitation on all ports except 80?

**Comment by sagikazarmark** [comment]
So, this is not the first time this issue comes up, but it's not one issue really.

## cURL options are not used

> failed to open stream: Cannot connect to HTTPS server through proxy [file] <...>/vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php

Since in this case you don't actually use cURL, it's no surprise that curl options doesn't work for you.

Although stream contexts [support](http://php.net/manual/en/context.http.php#context.http.content) proxy option, I am not 100% sure that it supports authentication too.

**So you need to make sure that you actually use the cURL handler."

## socks5:// transport doesn't work

I believe you can just use `tcp://`


## Authentication

As said above I am not 100% sure that stream contexts support authentication.

As for cURL, it does, but not sure it understands the `tcp://user:pass@host:port` form.

See:

- https://curl.haxx.se/libcurl/c/CURLOPT_PROXYAUTH.html
- https://curl.haxx.se/libcurl/c/CURLOPT_PROXYUSERPWD.html

For the moment you can pass these configurations as [curl options](http://docs.guzzlephp.org/en/latest/faq.html?highlight=curl#how-can-i-add-custom-curl-options).

An alternative solution would be to parse the proxy URL and see if it contains a user/password pair, but that still lacks the authentication method. First I would try using the curl options above (see the PHP constants here: http://php.net/manual/en/curl.constants.php)

/cc @DenoBY

**Comment by itbdw** [comment]
What should I do if just wanna add configuration below. 

```
            $param[CURLOPT_PROXY] = "127.0.0.1";
            $param[CURLOPT_PROXYPORT] = "1080";
            $param[CURLOPT_PROXYTYPE] = CURLPROXY_SOCKS5;//this must be added
```

**Comment by itbdw** [comment]
@sagikazarmark help ...

**Comment by sagikazarmark** [comment]
Hm, it works for me.

`ssh -D 8123 $USER@localhost`

``` php
<?php

require __DIR__.'/vendor/autoload.php';

$client = new GuzzleHttp\Client();

$result = $client->get('https://google.com', ['proxy'=>"socks5://127.0.0.1:8123", 'timeout'=>1]);

echo $result->getBody();
```

Which PHP version do you use? Are you sure you use the cURL handler?

The timeout operation indicates that Guzzle either tried to connect to the host, but it couldn't (because without the proxy it cannot access the host?) or it connected to the proxy, but for some reasons the HTTP request failed.

If it tried to connect to the proxy without success you would see a message like this:

`Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 7: Failed to connect to 127.0.0.1 port 1080: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'`

**Comment by itbdw** [comment]
Well.

1. I do the test in China. It means google was blocked.

2. I set the socks5 proxy by shadowsocks. It was a nice tool you can search it on github，the one with defalt rm branch and you can just switch master. 

3. When I use guzzle. I can see it was connected to shadowsocks local client but it just give me a regular cURL timeout error as if I did not use the proxy. But it was fine with php curl_* . Weird.



发自我的 iPhone

**Comment by xjchengo** [comment]
@itbdw 
replace scheme `socks5` with `socks5h`. So try this:
```
$client = new GuzzleClient();
$result = $client->get($url, ['proxy'=>"socks5h://127.0.0.1:1080", 'timeout'=>1]);
```

**Comment by itbdw** [comment]
@xjchengo 

Great! It works.

When I use curl_*, and add a `[CURLOPT_FOLLOWLOCATION=>true]` option with `socks5://`, it failed just like what I encountered with guzzle. `socks5h://` works fun.

So, maybe there is something guzzle used changed the curl behavior.

cc  @sagikazarmark

**Comment by sagikazarmark** [comment]
Okay....seems quite strange. I am trying to reproduce these errors for months now without any success. I will give it another shot once 6.3 is released. Thanks for the input.

**Comment by xjchengo** [comment]
```
$result = $client->get('https://google.com', ['proxy'=>"socks5://127.0.0.1:1080", 'timeout'=>1]);

echo $result->getBody();
```
Then reason that above code works fun for @sagikazarmark but not for @itbdw is DNS difference.
When using socks5, hostname will be resolved locally. `GET https://google.com` will be redirected to `https://www.google.com`. But DNS cannot resolve right ip of `www.google.com` in circumstance of @itbdw. When using `socks5h`, hostname will be resolved by proxy.

-------------------------------------------------------------------------------------------------------------
```
$ch = curl_init('https://google.com');
curl_setopt($ch, CURLOPT_PROXY, "socks5://127.0.0.1:1080");
```
Because `guzzle` default allow redirects but `curl` doesn't. So if above code works, following code may work also.
```
$result = $client->get('https://google.com', ['proxy'=>"socks5://127.0.0.1:1080", 'timeout'=>1 'allow_redirects' => false]);

echo $result->getBody();
```

**Comment by sagikazarmark** [comment]
@xjchengo thank you very much for the investigation.

**Comment by itbdw** [comment]
@xjchengo @sagikazarmark 

Just like @xjchengo said, when I add a `CURLOPT_FOLLOWLOCATION=>true` option, same thing happened.

This is the final investigation result I believe. Thanks again to @xjchengo

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by gpressutto5** [comment]
Any update on how to use SOCKS5 proxy with guzzle? None of the above worked for me...
```php
// tried using socks5 
'proxy' => 'socks5://localhost:8080',

// tried using socks5h
'proxy' => 'socks5://localhost:8080',
```
Also tried using ALL_PROXY on my env file
```env
ALL_PROXY=socks5://localhost:8080
```

**Comment by yoander** [comment]
This issue is related with libcurl version:

`Since 7.21.7 the proxy string supports the socks protocols as "schemes".`

https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by BenMorel** [comment]
The issue for me is that the `socks5://` proxy scheme only works with `CurlHandler`, which is fine most of the time, until you start using the [stream](http://docs.guzzlephp.org/en/stable/request-options.html#stream) option: Guzzle then transparently switches to the `StreamHandler`, which supports streaming but does *not* support `socks5://` or `socks5h://`, and does not seem to support SOCKS5 via the `tcp://` scheme either.

So you're using your SOCKS5 proxy with Guzzle and everything works fine. Then you attempt to stream a response and you suddenly get:

> Error creating resource: [message] fopen(http://...): failed to open stream: Unable to find the socket transport "socks5h" - did you forget to enable it when you configured PHP?

This is all very confusing and should at least be documented.

**Comment by ndobromirov** [comment]
@BenMorel If I understand this correctly, this is either `allowing the use of the socks5 proxy` OR `allow for concurrent requests through Guzzle`.

Is there ANY way to have them both?

**Comment by BenMorel** [comment]
@ndobromirov IIRC, no, this prevents from using **socks5** and [streaming of the response](http://docs.guzzlephp.org/en/stable/request-options.html#stream) together.

I'm not sure but this shouldn't prevent from using **socks5** and **concurrent requests**, that are supported by `CurlHandler` AFAIK (ensure that you have the `curl` extension installed though!)

**Comment by ndobromirov** [comment]
Well in my case I have an API that I am consuming concurrently (code-wise) and the total time to fetch responses is increasing linearly.

```

**Comment by tone87** [comment]
for me work with SOCK5 protocol. need to setup option like this

```
$httpClient = new GuzzleHttp\Client([
    'proxy' => '127.0.0.1:1080', //use without "socks5://" scheme
    'verify' => true,
    'curl' => [CURLOPT_PROXYTYPE => 7],
]);
```

**Comment by bernardwiesner** [comment]
the only way I have gotten guzzle to work with both streaming and using socks5 is by doing:

```php
        $client = new Client();
        $client->get($url, [
            'curl' => [
                CURLOPT_PROXY => 'socks5://127.0.0.1:9050',
                CURLOPT_FOLLOWLOCATION => true,
                CURLOPT_WRITEFUNCTION => function($curl, $data) {
                    // ... your streaming logic
                    return strlen($data);
                }
            ]
        ]);
```

Which is basically using underlying curl features. 

Without streaming it works fine just doing:

```php
        $client->get($url, [
             'proxy' => 'socks5://127.0.0.1:9050'
             // 'stream' => true -- does not work
        ]);
```

Trying to use the `stream` option together with proxy socks5, didn't work for me.
