### ISSUE TITLE
guzzle redirect and charset

### ISSUE THREAD

**Issue by jhonata-menezes** [guzzle/guzzle#1512]
I try to access the following address guzzle however is lost in the charset...
I guess

Example:

URL: PRE: http://www.licitacoes-e.com.br - necessary because of the set-cookie
URL: http://www.licitacoes-e.com.br/aop/consultar-anexo-licitacao.aop?opcao=consultarEdital&numeroLicitacao=630167&numeroAnexoLicitacao=1

PS:in the browser is done the correct redirection

``` php
$http = new \GuzzleHttp\Client(['cookies'=>true]);
$http->get('http://www.licitacoes-e.com.br/');
$response = $http->get('http://www.licitacoes-e.com.br/aop/consultar-anexo-licitacao.aop?opcao=consultarEdital&numeroLicitacao=630167&numeroAnexoLicitacao=1',['allow_redirects' => false]);
$http->get($response->getHeader('Location')[0]);
```

AND

``` php
$http = new \GuzzleHttp\Client(['cookies'=>true]);
$http->get('http://www.licitacoes-e.com.br/');
$http->get('http://www.licitacoes-e.com.br/aop/consultar-anexo-licitacao.aop?opcao=consultarEdital&numeroLicitacao=630167&numeroAnexoLicitacao=1');
```

any help will be welcome, thank you.

**Comment by mtdowling** [comment]
I don't understand the issue. Can you provide more information? What does the charset have to do with the redirect?

**Comment by jhonata-menezes** [comment]
Location with charset iso-8859-1

![dev-tools](https://cloud.githubusercontent.com/assets/7094378/25401965/b3ccc89a-29cd-11e7-9949-579277ff6256.PNG)

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
