### ISSUE TITLE
Getting cURL error 3 randomly

### ISSUE THREAD

**Issue by brazenvoid** [guzzle/guzzle#1518]
I am getting cURL error 3 malformed randomly as I request the API for data from my app. Its really is strange as when I request the API for a page information which actually is a group of 15-20 calls, it fails with that error the first time and succeeds in the second. 

I have had pasted the same question on stack with little to no responses. 
# Application Structure

The application is structured with a REST API for communicating with the main database. The front end also has a backend to mask the API calls. As each and every resource is sourced from the API, there are over 30 calls to the API which return whole swaths of JSON. but the actual data to the page is negligible. Most of the time is spent on rendering the views in Laravel.
## Guzzle Initialization and Usage

Guzzle client is initialized in the constructor of the main controller class and looks like this;

``` php
$this->apiClient = new Client(array(
    'timeout' => 3600,
    'headers' => array(
        'Accept' => 'redacted'
    )
));
```

The central location from where all API calls are made has the following code;

``` php
$response = $this->apiClient->request($httpMethod, $url, $callParameters);
```
# Behavior
1. After I refresh the page the first time, a CURL Error 3 (malformed) is always thrown.
2. There is a possibility that the second refresh will also throw it.
3. If not then there is a significant possibility that a DB access not allowed exception is thrown.
4. Usually the third refresh gets the page, just fine.
## CURL Error Behavior

This comes about 10-20 seconds after clicking the reload button.
## DB Error Behavior

The DB error is the one saying in the lines of database access not allowed for user 'root'@'localhost' with password No

This usually comes just after clicking the refresh button.
# Technology Stack
- PHP 5.6
- Laravel 5.2
- Guzzel 6 for communicating with the REST API
- MariaDB 10

I am slightly inclining towards Laravel now as sometimes there is also an error from DB like access not allowed for blah blah with password NO, but there is a password defined. The error doesn't appear for the next 100 or so requests.

**Comment by Tobion** [comment]
What does the DB errors have to do with Guzzle? Please try to create a minimum reproducible failure.

**Comment by sagikazarmark** [comment]
Nice issue @brazenvoid, thanks.

As @Tobion said we would need you to debug the problem and have some actual context about the moment the problem happens.

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
