### ISSUE TITLE
59 is not a valid cURL Multi Handle resource

### ISSUE THREAD

**Issue by MarioPerezEsteso** [guzzle/guzzle#1531]
Hi!
I am getting a warning related to Guzzle which is happening randomly and it is being logged millions of times (more than 3M warnings in 2 minutes). These are the two messages:

```
PHP Warning: curl_multi_exec(): 59 is not a valid cURL Multi Handle resource in /var/www/app/20160715081907/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 238
PHP Warning: curl_multi_info_read(): 59 is not a valid cURL Multi Handle resource in /var/www/app/vendor/guzzle/guzzle/src/Guzzle/Http/Curl/CurlMulti.php on line 254
```

Guzzle 5.2.0 and PHP 5.6

**Comment by mtdowling** [comment]
The only thing I can think of is maybe you're running HTTP requests in a destructor somewhere while your application is shutting down?

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
