### ISSUE TITLE
Error with Oracle based API

### ISSUE THREAD

**Issue by wipflash** [guzzle/guzzle#1553]
When I calling to a API It shows following error.
```
Server error: `GET http://my-api.dev/api/home/show` resulted in a `500 Internal Server Error` response:
{"message":"ORA-01017: invalid username\/password; logon denied","status_code":500,"debug":{"line":466,"file":"D:\\xampp (truncated...)
```
But if I used Postman It shows all data correctly. The API used Oracle 12c and its worked perfectly. Please give some advice.

**Comment by alexeyshockov** [comment]
There is not enough information to help. Specify your PHP code with Guzzle calls, give general information about Oracle endpoint's authentication (A specific header? Basic authentication?).

P.S. Probably your question is more suitable for StackOverflow, because there are (probably) no issues with Guzzle.
