### ISSUE TITLE
Async iterator rewind

### ISSUE THREAD

**Issue by cdekok** [guzzle/guzzle#1554]
When using the async method with an iterator it should hit the rewind function first before iteratoring over the requests else you could get unexpected results. 

In my case an sql iterator fetched the row on rewind: https://github.com/auraphp/Aura.Sql/issues/131

On guzzle 5.3

**Comment by mtdowling** [comment]
It's designed to specifically not call rewind so that you can pass it an iterator and the abstraction will not modify the state of the iterator in any way. Attempting to rewind a Generator that's been consumed always fails. Now, we could work around this by requiring people to provide iterators wrapped in a NoRewindIterator, but I think that would be a breaking change at this point.
