### ISSUE TITLE
Missing request object in async on v6

### ISSUE THREAD

**Issue by cdekok** [guzzle/guzzle#1560]
Currently in the async method it's not possible to use the request object on a successful response.
The previous interface had a get method for the request and response only the interface now only describes the response interface as argument is there any reason the request is not given as 2nd argument? 

I was using that mainly for debugging so it's not realy a big deal but it would still be nice to at least have the option to access the request or is there another way to do it now?

**Comment by mtdowling** [comment]
This was removed in Guzzle 6 for several reasons: to simplify the API, remove unnecessary/unrelated data from a value object (i.e., creating a response should not require me to create a request), reduce circular references that were present in previous versions of Guzzle, and adhere to PSR-7 without needing to extend the PSR-7 interface (which would have resulted in lots of adapter wrapping).

You could create a wrapper/helper method that decorates a Guzzle client async call so that it stores a reference to the request being sent and chains the promise such that it changes the normal Guzzle promise return value of `Promise<ResponseInterface>` to something like `Promise<[ResponseInterface, RequestInterface]>`.
