### ISSUE TITLE
Guzzle Truck Factor

### ISSUE THREAD

**Issue by 2mferreira** [guzzle/guzzle#1581]
Dear **Guzzle** contributors,

I am Master's student investigating the importance of the idea of truck factors in Software Engineering.

As you know, [truck factor](https://en.wikipedia.org/wiki/Bus_factor) (aka bus factor) is defined as “the number of people on your team who have to be hit by a truck before the project is in serious trouble”.  By "serious trouble", we mean that it will very difficult to maintain the project (e.g., bugs will take more time to be fixed, new features will be delayed etc).

I would appreciate your contribution by answering two questions:

1) According to your experience, what number best represents the truck factor of **Guzzle**?

2) Who are the developers responsible for this truck factor (i.e., the name of the developers who are responsible for the TF result answered in the previous question)?

Mívian Ferreira
Master's Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by sagikazarmark** [comment]
@2mferreira I am not completely sure if it's the perfect timing to ask these questions :smile: 

The Guzzle maintainer team is changing at the moment. @mtdowling decided to move to the background and the PHP HTTP group is stepping in for maintenance. There are four active maintainers of the group, but it's still unclear who exactly will contribute to Guzzle in the near future.

I would say the bus factor is pretty good in our case, because everyone knows about every project, yet we have separate responsibilities in the group, so we can easily replace each other in case of absence (be it a holiday, or God save us from that, but an actual bus accident).

All in all, I am not sure if we can answer your questions at the moment.

**Comment by mtdowling** [comment]
This type of question isn't really an issue. Closing.
