### ISSUE TITLE
If the body of a request is modified in a middleware, the content-length header is not updated

### ISSUE THREAD

**Issue by magarzon** [guzzle/guzzle#1590]
When a request is sent, the PrepareBodyMiddleware set the HTTP Content-Length header with the size of the body content, but if another middleware modify the body (and that modification changes the size of the body), the Content-Length header remains untouched, and this can be a source of errors if the server relies on the value of that header.

Yes, you can modify the HandlerStack to put the custom middleware before the PrepareBodyMiddleware, but maybe should be better than the withBody method in Request class, and/or the modify_request function take in consideration the new body size and modify the Content-Length header

**Comment by sagikazarmark** [comment]
> but maybe should be better than the withBody method in Request class

Well, adding this to the Request class would be wrong because:

- It would follow the Multiple Responsibility Principle, and last time I checked SRP was the hot thing
- It would also break the Liskov substitution principle
- Stream objects are not immutable as such in some cases you might only be able to read a stream once

Not to mention Content-Length is optional.

The proper solution for this problem is what you mentioned: maintain the order of middlewares. Moving the responsibility of the pipeline to a VO is not something that I would like to see here.
