### ISSUE TITLE
ban access to system paths on shared hosting

### ISSUE THREAD

**Issue by nimasdj** [guzzle/guzzle#1596]
Hi,

Isn't it possible that some shared hosting ban access to these system paths or these files will be always accessible?
https://github.com/guzzle/guzzle/blob/master/src/functions.php#L160

**Comment by sagikazarmark** [comment]
Good question. Is there an actual error that you met?

**Comment by nimasdj** [comment]
Isn't cURL able to find default system path without this way? It seems it can. So why are you using this way?

**Comment by sagikazarmark** [comment]
Actually it tries to find the CA automatically then falls back to the list. The exception bellow contains information about the problem:

https://github.com/guzzle/guzzle/blob/master/src/functions.php#L197

Alternatively you can download a common ca to your path and configure it.

**Comment by sagikazarmark** [comment]
I am still not sure about your problem without the exact error. You should also ask your provider whether they block access. Or you can just download a CA.

**Comment by nimasdj** [comment]
I want to use it in my product and give it away. So I will not know if end-user can use it I guess sharedhosting may block access to paths and end-users are not tech to define their own ca.
I think libcurl can find system default ca, without any need to method you fave the link? No?

**Comment by sagikazarmark** [comment]
Yes, cURL can do that and this method actually tries to find that CA first:

https://github.com/guzzle/guzzle/blob/master/src/functions.php#L183-L189

But it only works if the PHP ini is configured/default is not changed.

This method provides help in case it does not work for any reasons. I don't think shared hosting may block access to these files, but if they do, you really can't do anything (apart from turning verification completely off) since falling back to default does not help either.

**Comment by nimasdj** [comment]
I meant for example why not letting libcurl find  '/etc/pki/tls/certs/ca-bundle.crt' or other paths, rather than searching path by php? libcurl cannot find it itself?

**Comment by sagikazarmark** [comment]
Please read the exception message that I linked above. Also the process cannot access the file if the permissions do not allow that.
