### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by mits-techreceptives** [guzzle/guzzle#1601]
I am getting below error : 
GuzzleHttp\Exception\RequestException
cURL error 60: SSL certificate problem: unable to get local issuer certificate
↵
Caused by: GuzzleHttp\Ring\Exception\RingException

how to fix this ? what parameters i am missing during configuration ?
i set up as shown in doc but still it throws error.
i am on window localhost and trying to setting mailgun yii2 extension in PHP.

**Comment by sagikazarmark** [comment]
Unfortunately I don't use Windows. @guzzle/maintainers can someone help here?

**Comment by ivanjaros** [comment]
Looks like guzzle ignores the curl.cainfo / openssl.cafile php settings.

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by still-dreaming-1** [comment]
I had a similar exception on Windows 10. I was able to follow the steps here to resolve it: http://docs.guzzlephp.org/en/stable/request-options.html#verify-option

For me I basically just had to download a CA Certificates file and set the curl.cainfo setting in my php.ini to the path of that file. I downloaded it from https://curl.haxx.se/docs/caextract.html
