### ISSUE TITLE
php7.0.11 and curl-7.15.5 curl_setopt_array error

### ISSUE THREAD

**Issue by duxphp** [guzzle/guzzle#1602]
vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php 57 line

curl_setopt_array() Array keys must be CURLOPT constants or equivalent integer values 

debug
foreach($conf as $key => $item) { if (strpos($key, 'CURLOPT_TIMEOUT_MS') !== false) { unset($conf[$key]); $conf[CURLOPT_TIMEOUT] = 60; } }

**Comment by sagikazarmark** [comment]
Can you please provide an example code which produces this issue?

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
