### ISSUE TITLE
Guzzle resolves all promises even when not asked to

### ISSUE THREAD

**Issue by bpolaszek** [guzzle/guzzle#1603]
Hello,

I'm currently working with promises in my application. 
These promises can be generated by the Guzzle Client, or by custom functions of my app. 
For some reasons, I need to control which promises are asked to be resolved (i.e. invoking wait()) and when.

To show you an example, let's get started with custom promises.

``` php

require_once __DIR__ . '/../vendor/autoload.php';

use GuzzleHttp\Promise\Promise;


$promise1 = new Promise(function () use (&$promise1) {
    $result = 1;
    var_dump($result);
    $promise1->resolve($result);
    return $result;
});

$promise2 = new Promise(function () use (&$promise2) {
    $result = 2;
    var_dump($result);
    $promise2->resolve($result);
    return $result;
});

$promises = [
    $promise1,
    $promise2,
];

$promises[0]->wait();
```

In this case, I expect the following output:

```
int(1)
```

And this is what I have. Perfect.

Now let's write a similar code, but letting the Guzzle Client create the promises:

``` php

require_once __DIR__ . '/../vendor/autoload.php';

use GuzzleHttp\Client;
use GuzzleHttp\Psr7\Request;
use Psr\Http\Message\ResponseInterface;

$guzzle = new Client();

$onFulfilled = function (ResponseInterface $response) {
    $json = json_decode((string) $response->getBody(), true);
    var_dump((int) $json['args']['id']);
};

$promises = [
    $guzzle->sendAsync(new Request('GET', 'http://httpbin.org/get?id=1'))->then($onFulfilled),
    $guzzle->sendAsync(new Request('GET', 'http://httpbin.org/get?id=2'))->then($onFulfilled),
];

$promises[0]->wait();
```

Here I also expect the following output:

```
int(1)
```

But here's the output:

```
int(2)
int(1)
```

As you can see:
- I only asked the 1st promise to wait
- Both promises have been resolved
- The order is random

Why that behaviour?
As both promise types are built upon the same interface, I'm expecting the same behaviour, regardless of the PromiseInterface implementation.

Thanks,
Ben

**Comment by jeskew** [comment]
Hi Ben,

All Guzzle promises share the same global task queue, and waiting on any promise will run all outstanding tasks on the queue. In your second example, both promises have a `then` handler, which  is invoked when the HTTP request to httpbin.org completes. Calling `sendAsync` twice places two tasks on Guzzle's queue, both of which executed when the first promise receives a call to `wait`. Which `$onFulfilled` callback is invoked first depends on the order in which the HTTP requests receive a response, so the output will not be the same each time the script is run. But since both HTTP requests received a successful response, both promises would be resolved.

**Comment by bpolaszek** [comment]
Hello jeskew,

Sorry for replying so late. Thanks for your answer.
I understand the point. Nevertheless, I still need to control when promises are to be executed, so I went to a custom implementation of Guzzle's `ClientInterface`, and it works as I expect.

Thanks for your help,
Ben

**Comment by kelunik** [comment]
@bpolaszek *When* promises are to be resolved is the sole responsibility of the creator of a promise. Your first example only works by accident.
