### ISSUE TITLE
How to log response to file , and not affect to get response in code?

### ISSUE THREAD

**Issue by maimake** [guzzle/guzzle#1644]
I know it is only one time to get response's content. But I want to log the response content, and than continue do something  in PHP. 

```php
    public function testLog()
    {
        $logger = new Logger('Test');
        $logger->pushHandler(new StreamHandler(storage_path('logs/test.log'), Logger::DEBUG));

        $stack = HandlerStack::create();
        $stack->push(
            Middleware::log(
                $logger,
                new \GuzzleHttp\MessageFormatter('{res_body}')
            )
        );

        $client = new \GuzzleHttp\Client(['handler' => $stack]);
        $res = $client->get('https://www.google.com');
        $this->assertNotNull($res);
        $this->assertNotNull($res->getBody());
        $this->assertNotEmpty($res->getBody()->getContents()); // Failed !!!
    }
```

**Comment by sagikazarmark** [comment]
`getContents`reads the remainder of a stream. Try rewinding the stream and casting it to string, but be aware, some streams cannot be rewinded.

**Comment by lhfeng** [comment]
hello, I run this code:

`    $log = new Logger('test1');
    $log->pushHandler(new StreamHandler('./test.log', Logger::DEBUG));

    $stack  = HandlerStack::create();
    $stack->push(Middleware::log($log, new MessageFormatter(MessageFormatter::SHORT), Logger::DEBUG));

    $client = new Client(['handler' => $stack]);
    $url = 'http://10.200.241.247/testGuzzle.php';

    echo $client->get($url) . PHP_EOL;`

get error:
  PHP Catchable fatal error:  Object of class GuzzleHttp\Psr7\Response could not be converted to string in /Users/echo/data/www/guzzle/example/test.php on line 401

I guess  Response class needs implement __tostring function:

` public function __toString()
    {
        return $this->getBody()->getContents();
    }`


ask：Is there a better way to do it? I don't want to change the source code.

**Comment by sagikazarmark** [comment]
Your logging code works just fine, in this case this is the guilty one:

`echo $client->get($url) . PHP_EOL;`

If you want to output the body of the response:

`echo $client->get($url)->getBody() . PHP_EOL;`

But you might want to rewind the body first (as I mentioned above)

`$body->rewind()`

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
