### ISSUE TITLE
break a pool

### ISSUE THREAD

**Issue by scne** [guzzle/guzzle#1681]
How can I break conditionally a pool if request is empty?
I've this kind of code

```
$requests = function ($total) {
    $uri = 'http://api.request';
    for ($i = 1; $i <= $total; $i++) {
        yield new Request('GET',$uri);
    }
};

$pool = new Pool($client, $requests(500), [
    'concurrency' => 2,
    'fulfilled' => function ($response, $index) {

        $myArray = $mapper->mapArray(
            json_decode($response->getBody($asString = TRUE)), new ArrayObject(), 'MyClass'
        );

        if(empty($myArray)) //in this case I would break all request

.........
```

Is it possible? Thanks

**Comment by sagikazarmark** [comment]
I don't think this is possible at the moment.

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
