### ISSUE TITLE
Getting Wrong Status Code (Getting 200 on 404)

### ISSUE THREAD

**Issue by Sidd27** [guzzle/guzzle#1689]
Hi I am using guzzle with laravel 
 Below is how I am making request to 
```
$client = new \GuzzleHttp\Client(array('headers'=>array('Accept'=>'application/json', 'Content-Type'=>'application/json')));
        $method = strtolower($method);
        $request=$client->post($apiUrl, (null == $params) ?:(is_array($params))
            ?['form_params' => $params]
            :['body' => $params]);
        $this->pr($request);die;
```

Below is the print_r() response
```
GuzzleHttp\Psr7\Response Object
(
    [reasonPhrase:GuzzleHttp\Psr7\Response:private] => OK
    [statusCode:GuzzleHttp\Psr7\Response:private] => 200
    [headers:GuzzleHttp\Psr7\Response:private] => Array
        (
            [Server] => Array
                (
                    [0] => nginx/1.8.1
                )

            [Date] => Array
                (
                    [0] => Fri, 16 Dec 2016 06:13:02 GMT
                )

            [Content-Type] => Array
                (
                    [0] => application/json
                )

            [Transfer-Encoding] => Array
                (
                    [0] => chunked
                )

            [Connection] => Array
                (
                    [0] => keep-alive
                )

            [Vary] => Array
                (
                    [0] => Accept-Encoding
                )

        )

    [headerNames:GuzzleHttp\Psr7\Response:private] => Array
        (
            [server] => Server
            [date] => Date
            [content-type] => Content-Type
            [transfer-encoding] => Transfer-Encoding
            [connection] => Connection
            [vary] => Vary
        )

    [protocol:GuzzleHttp\Psr7\Response:private] => 1.1
    [stream:GuzzleHttp\Psr7\Response:private] => GuzzleHttp\Psr7\Stream Object
        (
            [stream:GuzzleHttp\Psr7\Stream:private] => Resource id #252
            [size:GuzzleHttp\Psr7\Stream:private] => 
            [seekable:GuzzleHttp\Psr7\Stream:private] => 1
            [readable:GuzzleHttp\Psr7\Stream:private] => 1
            [writable:GuzzleHttp\Psr7\Stream:private] => 1
            [uri:GuzzleHttp\Psr7\Stream:private] => php://temp
            [customMetadata:GuzzleHttp\Psr7\Stream:private] => Array
                (
                )

        )

)
```
**And postman is giving me 404 but guzzle is giving me 200**
![image](https://cloud.githubusercontent.com/assets/17669399/21253552/a035ecb6-c385-11e6-839c-2edb0c4219ba.png)

**Comment by sagikazarmark** [comment]
In the code example you send two headers, whereas in Postman you send 7.

You could try to convert the created request object to cURL command using this tool: https://github.com/namshi/cuzzle

Then see what the response to that request is. If cURL gives the same response as Guzzle then there is a problem with your request. If it gives the same as Postman then you should examine your handler stack and request options (in this case you could create a middleware which formats your request with the tool above and writes it to a log, but make sure to place it as a final middleware, so that all request modifications in other middlewares are already happened by the time the request gets to this one).

**Comment by Sidd27** [comment]
@sagikazarmark the headers which are you saying about is of response not of Request
which below reponse also have
```
 [headers:GuzzleHttp\Psr7\Response:private] => Array
        (
            [Server] => Array
                (
                    [0] => nginx/1.8.1
                )

            [Date] => Array
                (
                    [0] => Fri, 16 Dec 2016 06:13:02 GMT
                )

            [Content-Type] => Array
                (
                    [0] => application/json
                )

            [Transfer-Encoding] => Array
                (
                    [0] => chunked
                )

            [Connection] => Array
                (
                    [0] => keep-alive
                )

            [Vary] => Array
                (
                    [0] => Accept-Encoding
                )

        )
```

**Comment by sagikazarmark** [comment]
Ah, that's why I don't use postman, always confuses me. 😛 

The rest still applies to find the reason.

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
