### ISSUE TITLE
No such file or directory, /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php↵[line] 312

### ISSUE THREAD

**Issue by manojsharma20** [guzzle/guzzle#1691]
Hi,

I have installed and try to connect a Rest API with Post, but i am getting "No such file or directory, /vendor/guzzlehttp/guzzle/src/Handler/StreamHandler.php↵[line] 312".

Please tell me the solution for the above issue.

**Comment by sagikazarmark** [comment]
Without further context I am not sure we can help. Have you checked if the file is there? What causes the error? Is autoloading correctly configured?

**Comment by Konafets** [comment]
@manojsharma20 Can you post your request here? I guess the URI in the request is not set or does not exist.

**Comment by sagikazarmark** [comment]
Oh, I missed that comma...

**Comment by Khadreal** [comment]
Has anyone found a solution to this error, am having same issue

**Comment by sagikazarmark** [comment]
Can you please provide more context? Without your Guzzle setup we can't really help...

**Comment by hhsissi** [comment]
Hi, This error occured in my app because base_uri option was missing protocole. I hope it helps someone (and exception message should probably be corrected).

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.

**Comment by sharpmos** [comment]
This issue still exists when you try making installations of drupal 8 versions
![error](https://user-images.githubusercontent.com/26614475/47220272-f7868980-d3b9-11e8-9847-76447a91007a.png)

**Comment by sheinavi** [comment]
In my case it was because I forgot to add my variables to .env file.
