### ISSUE TITLE
Problem with GET parameters

### ISSUE THREAD

**Issue by juanbiondi** [guzzle/guzzle#1696]
Hi! i have been trying to use the "Roads API" from google and i have encountered a problem. The api receive several positions and interpolates it in road coordinates, it works with GET parameters using a "|" as a separator between coordinates. 
The problem is that when i create the request, Guzzle "encodes" the GET parameters and replaces the "|" with the code "%7C".
I have encountered that getting the "query" is possible to disable the encoding but that is not possible with the current version of Guzzle.

Thanks in advance

**Comment by sagikazarmark** [comment]
And that is the desired behaviour. See https://developers.google.com/maps/web-services/overview#BuildingURLs

**Comment by danizord** [comment]
I'm having the same issue here. That happens because `Guzzle\Psr7\Uri` [always filters](https://github.com/guzzle/psr7/blob/1.3.1/src/Uri.php#L381) the query string.

Any ideia?

**Comment by sagikazarmark** [comment]
I'm not quite sure why it is a problem. The documentation linked about specifically mentions encoding.

**Comment by danizord** [comment]
@sagikazarmark my problem was that there is no way to disable query string encoding anymore in current version.

**Comment by mtdowling** [comment]
The "query" request option sends the value through PHP's http_build_query() function. if you want to use a different encoding strategy, you can pass a string value into the "query" request option and Guzzle will use it as-is.

> I'm having the same issue here. That happens because Guzzle\Psr7\Uri always filters the query string.

This is a separate, slightly related, issue from the original reporter. Guzzle's PSR-7 functionality only encodes characters that MUST be encoded for them to be valid. It also does not double-encode characters that are already encoded. Why is that an issue?

**Comment by danizord** [comment]
@mtdowling nvm, I thought it was `Psr7\Uri` that was double-encoding my query string, but actually it is the `ValidatedDescriptionHandler` that is causing my param to be double-filtered, as reported in https://github.com/guzzle/guzzle-services/issues/134. I have proposed a fix in https://github.com/guzzle/guzzle-services/pull/135.

**Comment by sagikazarmark** [comment]
This issue was automatically classified as stale because it lacks information or cannot be reproduced.

If you think the issue is still valid and/or misclassified, please comment on the issue thread
and provide additional information (if possible).

Also, since the time maintainers can spend on the project is limited, please provide
a possible solution if possible, especially if it involves a platform that we cannot
test ourselves (Windows, very old/specific PHP versions, etc).

Issues marked as stale with no further activity will be marked as `rotten`
at some point and will automatically be closed within 14 days.

We do this so that we can focus on high priority issues. Thank you for your understanding.
