### ISSUE TITLE
Get full request and response as string without a ClientException 

### ISSUE THREAD

**Issue by gadelkareem** [guzzle/guzzle#1744]
I am trying to get the complete request and response as a string while there is no ClientException. For ex:
```
        $request = new Request(
            $resource->getMethod(),
            $resource->getUri(),
            $resource->getHeaders()
        );
        $response = null;
        try {
            $response = $this->client->send($request, $resource->getOptions());

            $resource->assertValidResponse($response);
        } catch (Exception $exception) {
            throw new MyException($request, $response, $exception);
        }

        echo Psr7\str($request);
        echo Psr7\str($response);
```

I understand I could log it using debug but I would like to see the final constructed request and response with final headers within the code.

**Comment by Konafets** [comment]
The request is not final at this point because it might get "changed" within the `send()` by some middleware. You could use the [history](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L80) or the [log](https://github.com/guzzle/guzzle/blob/master/src/Middleware.php#L185) middleware.

[How to use the History middleware](http://docs.guzzlephp.org/en/latest/testing.html#history-middleware)

Alternatively you can use an IDE and look into request and response while debugging it.

**Comment by gadelkareem** [comment]
Thank you for the tip. I know that it is a design thing but why request object is not modified by the `send()` so we can easily rely on it getting the exact request?

**Comment by Konafets** [comment]
It is modified because the default or your custom middleware is applied to the request _down the road_ before it is actually send over the wire. This gives you as a consumer the possibility to modify the request. Same happens with the response _up the road_. 

In one of my projects my client consumes an API which has very weird error responses (not following any HTTP error standard at all). I wrote a middleware which rewrites the HTTP error codes by peeking into the error messages. So its a mapping from "weird custom API messages to standardized HTTP status codes and messages".

Same was done in Guzzle < 6 with the Event System.

**Comment by gadelkareem** [comment]
I understand the concept and I might be wrong but I think that the middleware can still modify the request to achieve the same result. As far as the request is actually being built by the client, why would we make it immutable? especially the instantiated request does not give any real info about the final request which makes it a useless object. Moreover, while creating async requests, it might be very hard to extract the final request based on the transactions from the middleware.

**Comment by Konafets** [comment]
Have a look at [PSR-7](http://www.php-fig.org/psr/psr-7/) and the [implementation of it](https://github.com/guzzle/psr7) which is used by Guzzle6. This might answer your qeustions.

I'll close this issue because this is a building block of Guzzle6 and won't be changed.
