### ISSUE TITLE
version gets stripped when trying to set base_uri

### ISSUE THREAD

**Issue by Chrisissorry** [guzzle/guzzle#1803]
Hi, I instantiate the GuzzleHttp\Client like this:

```PHP
$client = new Client([
            'base_uri' => "https://us15.api.mailchimp.com/3.0/", 
            'auth' => [
                'username',
                $apiKey
            ]
        ]);
```

But get the following error:

```GuzzleHttp\Exception\ClientException: Client error: `GET https://us15.api.mailchimp.com/lists` resulted in a `404 Not Found` response:````

As you can see, the version is missing from the URL. How can I set it?

I am using version 6.2.3.

**Comment by sagikazarmark** [comment]
How do you call the client afterwards? More specifically: do you send the request to `list` or `/list` URI. I guess it's the latter, that's why it doesn't work for you.

We have tests for this behaviour: https://github.com/guzzle/psr7/blob/507a945c21614078a6fc78dada5938bf767e7a7d/tests/UriResoverTest.php#L70

**Comment by sagikazarmark** [comment]
Did you have any chance to take a look at this?

**Comment by gmponos** [comment]
Closing as no feedback has been provided. 

Feel free to provide more feedback and we can reopen the issue.
