### ISSUE TITLE
NTLM authentication missing from Version 6.2.3

### ISSUE THREAD

**Issue by avadaneidanut** [guzzle/guzzle#1831]
**Hello guys,**

I've spent few hours debugging and trying to figure out why the NTLM authentication is not working and I've just saw that the 6.2.3 version doesn't have it included.

```php
switch ($type) {
    case 'basic':
        $modify['set_headers']['Authorization'] = 'Basic '
            . base64_encode("$value[0]:$value[1]");
        break;
    case 'digest':
        // @todo: Do not rely on curl
        $options['curl'][CURLOPT_HTTPAUTH] = CURLAUTH_DIGEST;
        $options['curl'][CURLOPT_USERPWD] = "$value[0]:$value[1]";
        break;
}
```

The [documentation](http://docs.guzzlephp.org/en/latest/request-options.html#auth) and also the [master branch](https://github.com/guzzle/guzzle/blob/master/src/Client.php#L355) include this feature, correct me if I am wrong, shouldn't it be included in v6.2.3 also?

**Comment by sagikazarmark** [comment]
Sorry, this is not the first time this issue comes up. The feature is already merged in master and will be part of the 6.3 release. Unfortunately the default documentation version is `latest`. If you switch to `stable` at the right bottom corner of the page it should be gone.

Ping @mtdowling (can we make the stable version the default?)

**Comment by garethellis36** [comment]
This issue got me as well. Lost half an hour or so debugging...

**Comment by sagikazarmark** [comment]
Sorry for the trouble. guzzlephp.org now redirects to the stable documentation, not the latest one. 6.3 release will follow shortly.
