### ISSUE TITLE
Files are not sent (using 'multipart' when header 'Content-Type' is set manually)

### ISSUE THREAD

**Issue by jeromejaglale** [guzzle/guzzle#1885]
| Q            | A
| ------------ | ---
| Bug?         | not sure
| Version      | 6.3.0

#### Actual Behavior

When using 'multipart', the form data is not sent when the global header 'Content-Type' is manually set to 'multipart/form-data'.

#### Possible Solutions

Mention in the documentation, under the 'multipart' section, that 'Content-Type' shouldn't be set manually.

**Comment by tomzx** [comment]
Do you mean you're doing something like the following request?

```php
$response = $client->request('POST', 'upload.php', [
    'headers' => [
        'Content-Type' => 'multipart/form-data',
    ],
    'multipart' => [
        [
            'name'     => 'test',
            'contents' => fopen('index.php', 'r'),
        ]
    ],
]);
```

Files are still sent to the remote server (as observed by outputting `$_SERVER['CONTENT_LENGTH']`), but the server will generate the following warning `Warning: Missing boundary in multipart/form-data POST data in Unknown on line 0`.

**Comment by mubat** [comment]
I think, this is because the client does not attach the value of the boundary to `Content-Type` header.
Request from guzzle came with `'Content-Type' => 'multipart/form-data',` only, but from browser header is `'Content-Type' => 'multipart/form-data; boundary=-----44cf242ea3173cfa0b97f80c68608c4c' for example request:
```http
-----44cf242ea3173cfa0b97f80c68608c4c
Content-Disposition: form-data; name="image_01"; filename="lorem-ipsum.png"
Content-Type: image/png; charset=binary

�PNG
���...etc etc...
���,
-----44cf242ea3173cfa0b97f80c68608c4c
Content-Disposition: form-data; name="testkey"

testvalue
-----44cf242ea3173cfa0b97f80c68608c4c
Content-Disposition: form-data; name="otherkey"

othervalue
-----44cf242ea3173cfa0b97f80c68608c4c--

```

**Comment by kvnvandenbrande** [comment]
I spent a day looking for a solution this issue.. The removal the manual header was the solution. The suggested solution from @jeromejaglale would have helped me much faster in finding the problem!

**Comment by crjaCC** [comment]
I just had this same issue.

**Comment by thucpug** [comment]
can you show code post image by form data as your reply

**Comment by ksgush1** [comment]
Wow! Yes a hint in the docs would have saved a ton of time.

**Comment by roelywoely** [comment]
Another day of debugging here as well, would be great if this would be added to the docs.

**Comment by jordanyoungs** [comment]
Commenting because I also spent a day trying to debug this. +1 to the suggestion that it should be mentioned in the documentation

**Comment by Nyholm** [comment]
@roelywoely and @jordanyoungs: feel free to open a PR

**Comment by gabrielrbarbosa** [comment]
2024 and still lost a day debugging this and the API errors.
If the header is set by guzzle why not internally checking this condition?

**Comment by kadusalles** [comment]
Same here, I spent quite a bit of time thinking it was something to do with file encoding or the way I was reading it. But in the end, it turned out to be the header.

Perhaps if the manual header could be ignored, why not implement a condition to ignore it to avoid errors? Or at the very least, raise an exception to indicate that the header is the problem. This could be very helpful for others.

**Comment by WebCimes** [comment]
The issue with Guzzle is that manually setting the Content-Type header for a multipart request prevents Guzzle from automatically generating the boundary. The boundary is essential in multipart/form-data requests, as it separates the different parts of the request body (e.g., files, form fields). When Content-Type is specified manually, Guzzle does not generate or add this boundary, leading to server errors because the request format is incomplete or incorrect.

After 7 years, maybe it’s time for Guzzle to add the boundary even if a Content-Type header is already defined?
