### ISSUE TITLE
Slow GuzzleHttp\Handler\CurlMultiHandler::tick() with SQS

### ISSUE THREAD

**Issue by moeseth** [guzzle/guzzle#1898]
Hi,

Guzzle tick() has been really slow with SQS.

<img width="997" alt="screen shot 2017-08-10 at 11 17 45 pm" src="https://user-images.githubusercontent.com/534443/29181702-2500f8d0-7e22-11e7-9c71-61d2246b4fab.png">

My curl version is 

`curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP`

It happens very often.

How can I debug it?

Thanks.

**Comment by alexeyshockov** [comment]
It's normal.

It just means that you spend almost the same time waiting for SQS as the whole communication time for it (`External` on the picture). If you don't use [async requests](http://docs.guzzlephp.org/en/stable/faq.html#can-guzzle-send-asynchronous-requests) then it's definitely correct, because you wait for SQS exactly inside `tick()`. If you use async requests, it means that you don't have any other work to perform in parallel and you (again) wait inside `tick()`.

**Comment by moeseth** [comment]
@alexeyshockov so, I can consider that it's because SQS has been slow at the particular time?

**Comment by alexeyshockov** [comment]
Don't know if 8000 ms means slow :) Depends on the amount of requests to it.

But there are definitely no issues with Guzzle.

**Comment by sagikazarmark** [comment]
Thanks for the answer @alekseykuleshov 

I couldn't be more accurate
