### ISSUE TITLE
How to use ETag & Last-Modified using this library

### ISSUE THREAD

**Issue by rajjanorkar** [guzzle/guzzle#1905]
I would like to only fetch the contents from remote if ETag or Last-Modified is changed. 

Basically i am fetching feeds from server every 10 mins, i don't want to get content every time i use get, instead i want to first check if the contents are changed, if yes then get the contents else don't.

This library is awesome, i read documentation, Looks like  i missed something so i don't know how to achieve  above.  Can any one please help.

Thank you.

**Comment by alexeyshockov** [comment]
To support this scenario you have to store old versions somewhere.

Take a look at [Kevinrob/guzzle-cache-middleware](https://github.com/Kevinrob/guzzle-cache-middleware). It's exactly what you are searching for. Just not in the core (Guzzle has a tiny core and a lot of extensions — middlewares).

**Comment by rajjanorkar** [comment]
Thank you @alexeyshockov 

Which old version you are referring?

I was thinking it is supported in this library and dont need any other library just for that.

**Comment by alexeyshockov** [comment]
By "old versions" I mean that you have to store the content of crawled pages somewhere to be able to send `ETag` or `If-Modified-Since` headers (all these headers mean that you have previous version of the page, from which you can calculate a hash (for `ETag`) or send the time of the last visit (for `If-Modified-Since`)). `guzzle-cache-middleware` solves that.

An HTTP client doesn't have to support `ETag` and `If-Modified-Since`, because of that it's not in the core.

**Comment by rajjanorkar** [comment]
Thank you Alexey,

Got it now, yeah you are right i am already storing those details in
database for the given url/feed. I think i got it as i have those details i
can simply add those into the http header and send get request. Then server
should send me response depending on my ETag and Last-Modified header
values.

**Comment by alexeyshockov** [comment]
@rajjanorkar, that's correct.

BTW, you can close the ticket if the question is answered :)

**Comment by sagikazarmark** [comment]
I believe it is, so closing. Feel free to reopen if unanswered questions remained, although StackOverflow might be a better place to ask questions like this.
