### ISSUE TITLE
Why the Client configuration methods are all private?

### ISSUE THREAD

**Issue by GusAntoniassi** [guzzle/guzzle#1954]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | 6.3.0

Hello, I would like to know if there is a reason for the `GuzzleHttp\Client` class to have most of its configuration methods (like `prepareDefaults`, `configureDefaults`, `buildUri` and so on) declared as `private` instead of `protected`.

I am trying to extend the class to implement my own client, and these configuration methods would be very handy if I could access them on my class.

Was this a design decision? Would there be any problem to set them as `protected`? I would be willing to submit a PR if there is no problem.

Thanks in advance for your attention.

**Comment by sagikazarmark** [comment]
Yes, there is: because they are not meant to be extended. :) In fact, the Client class itself is not meant to be extended either. If you need some custom logic, composition and middlewares provide almost everything you might need.

What are you trying to achieve?

> Was this a design decision?

Unfortunately it wasn't conscious decision in the past, but it is now, so in the next major release there is a chance that the client will be final too.

> Would there be any problem to set them as protected?

Many people argue creating final classes, so here is an another argument why we can't open those methods: it would be a BC break. Any class, extending the Client, implementing a custom method with the same name would break, since the protected method's signature could potentially break existing methods with other signatures. This is an edge case, probably noone reimplemented those methods ever, still it's there, providing proof why extending classes is actually a bad idea in so many cases and we kinda abuse inheritance.

**Comment by GusAntoniassi** [comment]
I am trying to develop a "fake" HTTP client with the same interface as Guzzle. 

My team and I have an application where the API may or may not be in the same server as the application source code, so we are trying to create a Client with the same methods as Guzzle, but instead of sending HTTP requests we just search the routes and invoke the action needed.
We are doing it this way so that if we ever have to separate the API from the application all we would have to do is tell the container to use Guzzle, no additional changes needed because all the method calls would be following Guzzle's signatures.

The problem I am having is that I need to call `buildUri`, `applyOptions` and `invalidBody` from Guzzle client to make the `$options` array identical to the Guzzle configuration. 

I am analyzing the code for Client again, and I realized I overlooked the 'handler' config. I am going to test it out tomorrow, but do you think I could use it to create my own "non-HTTP" handler? That would eliminate the need for a class extending Guzzle.

Kind regards.

**Comment by gmponos** [comment]
Why not using `ClientInterface` of guzzle?

**Comment by sagikazarmark** [comment]
@GusAntoniassi well, your use case is perfectly valid, and it's possible to do it using Guzzle:

1. You can rely on the `ClientInterface` in your code as @gmponos pointed out. This is probably a simplest and cleanest solution.
2. You can indeed override the handler, or even better write a custom middleware, place it on the top of the middleware chain (or wherever you need it) and only propagate requests to the actual handler which are not HTTP calls to your API. You can simply check the request object and decide what to do: stop the middleware chain or pass the request to the next middleware.

> to make the $options array identical to the Guzzle configuration.

Not sure I understand this part.

Allow me to suggest an alternative solution: don't use Guzzle at all. Create a custom interface for your API, implement a dummy version, which calls your API through your local project. Then when the time comes, you can simply implement the wrapper interface using an HTTP Client (like Guzzle or HTTPlug).

This probably requires a bit more work, but in the beginning it's easier to start and is much-much-much cleaner solution than relying on Guzzle, especially since you don't actually send HTTP calls at the moment. Not to mention, that you would have a complete SDK to your API in the end which you could even publish.

You can find more practices about API SDK-s here: https://github.com/FriendsOfApi

**Comment by GusAntoniassi** [comment]
Just to close this issue, I'd like to document how I ended up implementing things.

> Why not using ClientInterface of guzzle?

Wouldn't help me much, because I needed the functionality of `buildUrl`, `configureDefaults` and so on. What I did was:
- Create my own Client class with a private `Guzzle\Client` property (using composition as suggested by @sagikazarmark). This client routes all `request`, `post`, `get` and some other method calls to Guzzle, and implements some needed business logic.
- Create an InternalRequestHandler, which looks through the Router to find the requested class and invoke it.
- Create a couple of middlewares to implement some pre and post-request logic (authentication, serialization and so on).
- Put it all together on a HandlerStack and inject it to the Guzzle client through a custom factory.

The only thing I felt was missing (and I'd like to leave here as a suggestion -- do I need to open another issue for that?) was a HandlerInterface. It would be something very basic, just with the `invoke` signature, but having one would mean I could retrieve and store the handler in the application's dependency injection container. I ended up making an alias for the `DefaultHandler` which resolves to my `InternalRequestHandler`, but having an interface for that would be a lot better.

Thanks a lot for everyone who helped me! Very kind regards.
