### ISSUE TITLE
replace a middleware in HandleStack by name

### ISSUE THREAD

**Issue by renanbr** [guzzle/guzzle#1955]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | master

#### Actual Behavior

I didn't found an way to replace a middleware in the HandleStack.

#### Expected Behavior

Before making a request I would like to make sure a middleware is in the HandleStack by replacing it with the instance I have in hands, or adding it as usual.

#### Possible Solutions

Create `HandleStack::replace($name, $middleware): bool`, returns `true` if middleware was found and replaced, or `false` if middeware was not found, then users can decide where to place the middleware

**Comment by sagikazarmark** [comment]
Hm, interesting. Can you give me an example where this is useful? I would imagine that you only modify the stack at configuration time where you probably have all the middlewares at hand, but I could be wrong.

So a use case would be useful to understand what could really be the solution here. Thanks!

**Comment by sagikazarmark** [comment]
I see. In most of the cases I think it's better to provide an injection point for the user, but if you completely want to hide the transport layer from the user you still have a few options with the current featureset which may even be better.

What you want to do is directly hacking the HandlerStack runtime whereas you should probably configure it once and leave it alone. Immutable clients are usually working with some sort of builder to avoid runtime configuration changes, which is usually better.

If your API client is mutable, I would suggest storing your own configurations in the your client object and only construct the client for example before the first API call. That way you don't have to access the HandlerStack runtime. Every time you change something in your client, reset the build client and build it again on the first call.

Another thing you could do is wrapping the cache middleware with a custom middleware accepting a boolean setting cache on/off. Store that in your API object and set it's value. It's not that nice, but still slightly better IMO than accessing the handler stack.

So the order of my suggested solutions:

1. Make your API client immutable or use a builder
2. Rebuild the Guzzle client when something changes
3. Wrap the cache middleware with your own

I'm afraid adding such replace function would end up being massive abuse of state access and change in the HandlerStack. Also, since name uniqueness is not checked, IMO it's not really safe to rely on it in the first place.

Does this help solving your issue?

**Comment by renanbr** [comment]
@sagikazarmark Thank you for yout time and analysis
I think the solutions you propose fit to my case :-)
I'm closing this issue for now, someday i'll be back to share the solution adopted

**Comment by sagikazarmark** [comment]
Great, glad I could help
