### ISSUE TITLE
Keep getting BadMethodCallException from EasyHandle

### ISSUE THREAD

**Issue by Alluuu** [guzzle/guzzle#1959]
Hi,

All of a sudden when calling:
`$client->request('post', $endpointUrl, $requestParameters);`
or
`$client->requestAsync('post', $endpointUrl, $requestParameters);`

I get this following error and nothing else:

> The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">BadMethodCallException</em>: The EasyHandle has been released in <em class="placeholder">GuzzleHttp\Handler\EasyHandle-&gt;__get()</em> (line <em class="placeholder">90</em> of <em class="placeholder">vendor/guzzlehttp/guzzle/src/Handler/EasyHandle.php</em>).

Expected is either returned ResponseInterface implementing object or a RequestException (inheriting) exception, I receive neither. 

It may have something to do with changes on the queried server, but shouldn't there be RequestException thrown in these cases, when request response is not retrievable?

Any ideas how to resolve the issue or at least avoid everything crashing down? The behaviour is correct when I set a too small timeout, but when I set a timeout of 5 seconds, I get this error also.

Best,

Alari

**Comment by alexeyshockov** [comment]
Could you add the stack trace? It could help a lot to determine the reason of the exception.

Also, if it's possible, add all the details about the client. I mean all the options that you use to initialise Guzzle's `Client`: timeouts, etc.

**Comment by Alluuu** [comment]
Hi,

I'm using the client initialized by drupal with just 2 parameters:

`$request_options = array(
      'auth' => [self::$user, self::$pass],
      'form_params' => $request,
    );`

the rest of the code is:

`try {
      if (!$async) {
        $response = \Drupal::httpClient()->request('post', $uri, $request_options);
        return $this->encoder->decode($response->getBody()->__toString(), 'xml');
      } else {
        return \Drupal::httpClient()->requestAsync('post', $uri, $request_options);
      }
    } catch (RequestException $e) {
      dpm($e);
    }

    return FALSE;`

But even though the Exception is being caught and the dpm() inside the exception caught is fired, the EasyHandle still throws the error somewhere.

dpm is drupal variable dump using kint (in my scenario).

The dpm() tells me that the connection timed out: 
'errno' => integer28
'error' => string(66) "Operation timed out after 30000 milliseconds with 0 bytes received"

The stack trace is extremely horrifyingly long but after the dpm() is being fired in the error catching there's a lot of kintParser stuff for the dpm() and after that just 2 function calls of any relevance:

'36: ReflectionProperty->getValue()'
'37: GuzzleHttp\Handler\EasyHandle->__get()'

From which the latter already causes the error being thrown.

The ReflectionProperty get's argument GuzzleHttp\Handler\EasyHandle with following values:

→public sink -> GuzzleHttp\Psr7\Stream(7)
public headers -> array(0)
public response -> NULL
→public request -> GuzzleHttp\Psr7\Request(8)
→public options -> array(11)
public errno -> integer28
public onHeadersException -> NULL
public handle -> NULL

Unfortunately I don't have a clear way of dumping all the data in a readable way, the drupal ddebug_backtrace() is the only thing that put anything out and I had to parse it into html to read myself, running the kint script for formatting.

Best,

Alari

**Comment by sagikazarmark** [comment]
Okay, so in fact you receive a RequestException with the message "Operation timed out....".

Any chance that the `dpm` stuff calls something that it shouldn't?

What if you just var_dump the exception?

**Comment by golubev** [comment]
I faced a similar issue. In my case I use Sentry for PHP errors and exceptions reporting. And each time a connection via Guzzle timed out I was getting a white screen with the text:
```
BadMethodCallException
The EasyHandle has been released
```
instead of the graceful 5xx error page.

The problem in my case was caused by a serializer for vars from the errors stack trace. My user defined serializer was getting the values for every property of every var using the `ReflectionClass`. And when the serializer was trying to get the `handle` property from the `GuzzleHttp\Handler\EasyHandle` the next code from Guzzle was throwing exception:
https://github.com/guzzle/guzzle/blob/0773d442aa96baf19d7195f14ba6e9c2da11f8ed/src/Handler/EasyHandle.php#L85-L91

Fixing the serializer worked for me.

@Alluuu, maybe `dpm` was doing something similar in your case.

**Comment by joachim-n** [comment]
I'm seeing this problem with Drupal's Devel module too.

The problem seems to be that there's a warning in Guzzle somewhere, which Devel is then handling with its custom PHP error handler. 

That passes the backtrace to Devel's dpm() function, which hands over to Kint, which does this:

```
ReflectionProperty->getValue(Object) (Line: 496)
kintParser::_parse_object(Object, Object) (Line: 115)
```

It looks like getValue() is crashing because the object is a resource that's been released.

Unfortunately, it looks like there there's no simple way in PHP to check that something is a released resource. The fix would be for Kint to check for that and then skip it.

**Comment by ethernidee** [comment]
Same thing here. Generating debug dump on error throws \BadMethodCallException.
Officially public properties must not generate exceptions on access.

Had to add the following code to __get method:
```php
if (in_array($name, ['handle', 'sink', 'headers', 'response', 'request', 'options', 'errno', 'onheadersexception'])) {
    return null;
}
```
