### ISSUE TITLE
Long running Guzzle Pool don't close connection (Too many open files)

### ISSUE THREAD

**Issue by darkot013** [guzzle/guzzle#1977]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.2.3
| OS      | Ubuntu 14.04
| PHP      | 5.5.9
| Framework      | Symfony 2.3

####  Info

I make PDF Downloader who need to download few millions (20m~) PDF from some website and I plan to download (and save) all this PDF with Guzzle Pool system. I also use 100 proxy for this downloader.

When I use Pool system process create (but not close) too much "socket:[xy]" files in "/proc/{pid}/fd/" and in few minutes system kill that process and throw exception "failed to open stream: Too many open files in" on saving pdf part. I think that save pdf part not a problem because I make separate script and run at the same time 10x for saving and I don't hit system limit.

1. I increase "/proc/sys/fs/file-max" to "800.000" but this is not help. 
2. Change solf (from 1024 to 4096) and hard (to 8192) in "/etc/security/limits.conf " for every user (just to test) and also this is not help... Changes only postponed this exception... I track open files for running process (ls /proc/{pid}/fd | wc -l) and number of files it's only increases and when it's hit 4096 server kill that process.

When I check "lsof -i -a -p {pid}" I got a lots "CLOSE_WAIT" connection. 

Command: [source code](https://github.com/guzzle/guzzle/files/1555852/script.php.zip)
Note 1: I remove some part of code because some sensitive data. 
Note 2: "ArticleFiles->save()" only have "file_exists" and "file_put_contents".

------

I'm not sure but I'm think that Guzzle Pool have problem with long running command because don't close socket connections.

**Comment by darkot013** [comment]
Solved.

I add this config and now I close TCP connection (and script don't make lots files)
 - 'Connection' => 'close'
 - CURLOPT_FORBID_REUSE -> true
 - CURLOPT_FRESH_CONNECT -> true

**Comment by i-allan** [comment]
https://github.com/guzzle/guzzle/issues/1927 : can u share your findings in details here as well ?

**Comment by pratik-joshi-cactus** [comment]
We tried using the solution but didn't work. It still creates multiple sockets.
```

        $guzzle = new Client(
            [
                'Connection' => 'close',
                CURLOPT_FORBID_REUSE => true,
                CURLOPT_FRESH_CONNECT => true,
            ]
        );

```
Could you please let us know what else did you do to make it work. Thanks.

**Comment by sagikazarmark** [comment]
Thanks for the detailed issue and the solution @darkot013 , sorry for not answering earlier, but as I can see you solved the problem. 😄 

This is not the first time the open file limit issue pops up, but it seems to me this is yet another different case related to cURL (while this issue is usually related to the stream handler).

When using HTTP 1.1 because of KeepAlive TCP connections can be reused, I will have to check what's the default behaviour, but I would say it's on by default. When you send the `Connection: close` header they should not be reused, thus closed. It sounds interesting though that with keep alive the number of TCP connections does not stop growing, I assume because they are not reused, but a new one is opened every time. If so, that's a bug, and should be investigated (whether curl ext or guzzle bug).

@pratik-joshi-cactus note that the above only fixes the issue when you use the CurlHandler and hit the same open connections problem.

Also, I believe your configuration is incorrect, see:

http://docs.guzzlephp.org/en/stable/request-options.html#headers
http://docs.guzzlephp.org/en/stable/faq.html#how-can-i-add-custom-curl-options

**Comment by arderyp** [comment]
Thanks for the info @sagikazarmark.  However, as far as my testing goes with Guzzle 6 on PHP 7.2, the curl options above seem to have no effect when using the `CurlHandler`.  Using the `CurlHandler` does, itself, seem to resolve the error for me, but doesn't seem to be compatible with async/promise based concurrent requests, which is a major problem.  See me comment on #1927 [here](https://github.com/guzzle/guzzle/issues/1927#issuecomment-431467861).

**Comment by michaelbutler** [comment]
I would like to point out that in the original recommended configuration, `Connection` is actually a request header, not a top level Guzzle option. so this should close out the connections:

```
$guzzle = new Client([
    'headers' => ['Connection' => 'close'], // Or simply add this to the request object
    CURLOPT_FORBID_REUSE => true,
    CURLOPT_FRESH_CONNECT => true,
]);
```

**Comment by arderyp** [comment]
@michaelbutler, @pratik-joshi-cactus [commented](https://github.com/guzzle/guzzle/issues/1977#issuecomment-351765309) that your and @darkot013's exact suggestions didn't work for them.  I confirmed that it didn't work for me either.  This issue continues to perplex me...

**Comment by michaelbutler** [comment]
@arderyp, looking at `@pratik-joshi-cactus`'s comment directly, it uses the incorrect syntax. `Connection` is a request header, not a raw guzzle option. that is why I was assuming it didn't work for them. ` Granted, this solution while worked for me, is much slower than using the defaults, because by not closing the connection every time with `curl_close`, there is a nice speed up of connection reuse (I assume?). I will continue digging in and then follow up on the linked issue https://github.com/guzzle/guzzle/issues/1927 since that one is open and has a bit more info. 

Specifically, I'd like to reduce the file descriptor (open files) leak _while_ maintaining a high level of speed and efficiency.

**Comment by arderyp** [comment]
Ahhh @michaelbutler, I see what you are saying... pardon my misunderstanding.  I just tested your exact code in my use case, and I still get the same results:

```
PHP Fatal error:  Uncaught ErrorException: Warning: include(/path-to/vendor/symfony/debug/Exception/FatalThrowableError.php): failed to open stream: Too many open files in /path-to/vendor/composer/ClassLoader.php:444
```

I think my initial confusion stemmed from the fact that I did already test your suggested approach, and commented about it in the other issue here (scroll to the bottom of the comment): https://github.com/guzzle/guzzle/issues/1927#issuecomment-429488906

I can't tell if your proposed solution works for some kind of basic linear use case, but I can say it does not work for my concurrency use case.  Even if those headers trigger connection closing at some network level, the basic problem seems to be that Guzzle (or maybe its the OS?) is outputting tmp files for each connection and isn't cleaning them up when they are no longer necessary.  I am not sure if it is Guzzle or the OS that eventually cleans up those tmp files, but testing suggests that it only happens once the active PHP session/process ends/dies/completes.  In other words, regardless of any options you give Guzzle, it doesn't seem to implement explicit handling of these tmp files, thus it doesn't clean them up when they are no longer needed, thus if you make enough requests in the same sessions, you will eventually hit this problem.
