### ISSUE TITLE
progress callback get resource as the first argument instead of downloadtotal

### ISSUE THREAD

**Issue by ghost** [guzzle/guzzle#1981]
as the title said, this is the result of `var_dump(func_get_args()); die; ` inside the progress callback

```
array(4) {
  [0] =>
  int(0)
  [1] =>
  int(0)
  [2] =>
  int(0)
  [3] =>
  int(0)
}
array(5) {
  [0] =>
  resource(116) of type (Unknown)
  [1] =>
  int(0)
  [2] =>
  int(0)
  [3] =>
  int(0)
  [4] =>
  int(0)
}

Press ENTER or type command to continue

```
i followed the code and i see that in CurlFactory you already shifting args if the first arg is a resource, so why is it sending a resource, and the function is called twice?

**Comment by gmponos** [comment]
curl requires the handler to be first.. This is a programming "trick" that we are proxying the `progress` callback passed by the developer in order to push the handler first.

will close this for now as it does not seem as a bug of guzzle.

for support questions you can use other channels as well as listed below: https://github.com/guzzle/.github/blob/master/.github/SUPPORT.md
