### ISSUE TITLE
Guzzle running on server A sending requests to server B on which the RAM gets full

### ISSUE THREAD

**Issue by blackFirefly** [guzzle/guzzle#2053]
| Q            | A
| ------ | ---
| Bug?         | no
| New Feature? | no
| Version      | 6.3.0

#### Actual Behavior

I'm using Guzzle on server A wich sends a lot of requests to the Shopware REST-API on server B. Now I have the problem, that several "php-fpm" processes are created on server B using more and more RAM until it is completely full.
As soon as I abort the import scripts on server A, the RAM on server B is freed again.

So my question is if Guzzle could cause this behaviour or if the source of the problem has to be somewhere else.

I was not able to find a solution to my problem yet. (Also contacted the Shopware support which did not solve the issue)

**Comment by sagikazarmark** [comment]
This is certainly not a Guzzle issue, even if the cause seems to be the HTTP requests that you send. You either try to send too much content, more than your server B can process or the software on server B is too memory heavy itself.

Either way, Guzzle itself cannot cause high memory usage in other servers.
