### ISSUE TITLE
Guzzle doesn't work with Laravel commands when visiting a https websites 

### ISSUE THREAD

**Issue by filtration** [guzzle/guzzle#2068]
- Laravel Version: 5.6
- PHP Version: 7.2
- Database Driver & Version: Mysql

### Description:

Using guzzle via a command doesn't use an ssl certificate, but works when using guzzle via a controller or route.

### Steps To Reproduce:

Download Guzzle:

php composer.phar require guzzlehttp/guzzle

Create a route in web.php:

```
Route::get('/', function() {
    $client = new \GuzzleHttp\Client(); 
    $res = $client->request('GET', 'https://google.com/');

    dd($res);
});
```

Which will work fine, but now create a command php artisan make:command TestCommand

and and the code to the construct:

```
public function __construct()
{
    $client = new \GuzzleHttp\Client(); 
    $res = $client->request('GET', 'https://google.com/');

    dd($res);
}
```

This will throw a ssl error, even though the certs are all working fine, as you can see via the route closure code.

**Comment by sagikazarmark** [comment]
This sounds like to be an environmental issue to me.

Since you haven't provided a Guzzle version (despite the issue template required you to) and what the SSL error means I assume you use the latest and the problem is an invalid CA.

When no CA certificate chain is provided Guzzle uses the following function to determine which CA bundle to use:

https://github.com/guzzle/guzzle/blob/master/src/functions.php#L160

Any chance that you have an INI configuration for the web driver and none for the CLI driver?

**Comment by filtration** [comment]
This was some odd issue with my environment.. whenever I was changing (what I thought) was my php.ini file, it turned out it was a phpapache.ini file. All fix, and I sincerely apologise.

**Comment by sagikazarmark** [comment]
No need to apologize.

**Comment by bdruhan** [comment]
I know this is a closed issue, but I may have a similar problem.  I have an app that uses an https  laravel backend that talks to another laravel server that does image processing.  The image processing server was initially http on google compute engine.  Everything was working fine.  In order to make the app compliant for new https rules for the app store, I added ssl certificate to google compute engine and changed all env variables and references to point to https instead of http. The app is working, can access my files on the backend, but when I try to use the image processor I now I get an error on the backend server saying "guzzle cURL error 6: Could not resolve host:".  I can ping the host.

Can you explain what @filtration needed to correct in his php.ini file?  I am new to laravel and php.  Do I need to add a copy of the CA file for the google compute engine on the backend server and put a reference in openssl.capath in php.ini?

Thanks
