### ISSUE TITLE
SSL23_GET_SERVER_HELLO - Port to open

### ISSUE THREAD

**Issue by fury118** [guzzle/guzzle#2092]
Hi

I use guzzle and it work good with personnal wifi, professionnal wifi and 4g connexion.
When i am connected to the job server i get  this error since some ports have been closed recently.

GuzzleHttp\Exception\ConnectException: cURL error 35: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

Which port do i need to open ?

Regards

**Comment by brbrowning21** [comment]
> You will get such error message when you request HTTPS resource via wrong port, such as 80. So please make sure you specified right port, 443, in the Request options.

[Source](https://stackoverflow.com/questions/15421050/node-request-getting-error-ssl23-get-server-hellounknown-protocol)

I have a feeling that when you're connected to the job server, the host your requesting is resolving to use HTTP instead of HTTPS. You could try opening port 80 (HTTP), or better, override the hostname in PHP to use HTTPS (port 443).
