### ISSUE TITLE
Cookie Persistent not working

### ISSUE THREAD

**Issue by hashsup** [guzzle/guzzle#2117]
| Q            | A
| ------------ | ---
| Bug?         |yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

Cookie aren't resend to new request

#### Expected Behavior

Cookie should be resent in new request

#### Steps to Reproduce

```
<?php

use GuzzleHttp\Client;

$client = new Client([
  'cookies' => true
]);

$request = $client->get('http://localhost/test.php');
print_r($request->getHeaders());
$request = $client->get('http://localhost/test.php');
print_r($request->getHeaders());
```

#### Test file

`<?php session_start([
    'cookie_lifetime' => 86400,
]);`

**Comment by gmponos** [comment]
I am really sorry but from the info provided I can not understand what the issue is about.

Please make sure there is a bug. If you need support please refer to other channels. Check here: https://github.com/guzzle/.github/blob/master/SUPPORT.md

If more info are provided I would be happy to reopen the issue.
