### ISSUE TITLE
504 Gateway Time-out when request is done within a web context

### ISSUE THREAD

**Issue by burzum** [guzzle/guzzle#2123]
#### Actual Behavior

If I trigger a get request from within a web context I'm always getting a `504 Gateway Time-out`, no timeout exception from the actual request.

This here seems to be similar but its a totally different version I guess. https://github.com/guzzle/guzzle/issues/975

I'm using `^6.3?` for Guzzle in my composer.json which points to 407b0cb880ace85c9b63c5f9551db498cb2d50ba at this momen.

```
λ .\nginx.exe -v
nginx version: nginx/1.13.8

λ php -v
PHP 7.1.15 (cli) (built: Mar  1 2018 02:04:08) ( NTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```

This is what I found in the nginx log:

```
2018/08/14 12:24:08 [error] 29708#18668: *1 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.178.21, server: subdomain.domain.tld, request: "GET /en/tests/index HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "subdomain.domain.tld"
2018/08/14 12:24:09 [error] 29708#18668: *3 upstream timed out (10060: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) while reading response header from upstream, client: 192.168.178.21, server: subdomain.domain.tld, request: "GET /api/invoicing/invoices HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "subdomain.domain.tld"
```

#### Expected Behavior

Getting a response no matter from where the code is executed.

#### Steps to Reproduce

Can we re-open this? It looks like I'm running into the same issue,

```php
$client = new \GuzzleHttp\Client();
$result = $client->get('http://subdomain.domain.tld/api/invoicing/invoices', [
	'headers' => [
		'Accept' => 'application/json'
	]
]);
dd((string)$result->getBody());
```

If I run the very same piece of code in a shell application, it just works! I've tested this within the CakePHP framework and within a plain frameworkless index.php served by the same server (Nginx).

#### Possible Solutions

Sorry, no idea! 😢

**Comment by burzum** [comment]
Got it, god damn PHP-FPM problem... :(

**Comment by tiagomatosweb** [comment]
@burzum Did you solve the issue? I'm facing the same issue.

**Comment by sagikazarmark** [comment]
@tiagomatosweb The 504 status code clearly states that this is a server side issue and has nothing to do with Guzzle.

**Comment by sagikazarmark** [comment]
@tiagomatosweb well, it can be a number of issues, so no guarantees that the answer will help you either. 😞 

The most common issue is php-fpm failing, which might not immediately be obvious since the webserver responds. Misconfiguration is also common, although it does not happen from one moment to the other. Another problem can be a long running script with a low timeout defined in the webserver. Hope this helps.

**Comment by tiagomatosweb** [comment]
@sagikazarmark I am not expecting guarantees, thought people are here to help.
Thanks for your inputs, but suddenly things started running again. Not sure what has happened. :)

**Comment by sagikazarmark** [comment]
Glad to hear!

**Comment by Roritharr** [comment]
I'm fighting a very similar issue, experiencing the gateway timeout on the call to wait for the promise, but only in very specific circumstances.

Because we are atm migrating from mod_php to php-fpm thats the biggest difference between an environment where the same exact code doesn't create this issue, where the environment where we use fpm creates it.

Any hints about how to debug this situation would be tremendous help.

**Comment by joe-scotto** [comment]
@burzum Please tell us your solution.

**Comment by burzum** [comment]
@joe-scotto sorry, I don't remember, it was something with the FPM settings AFAIR. :(
