### ISSUE TITLE
Autoload functions_include.php files instead of functions.php

### ISSUE THREAD

**Issue by takkaria** [guzzle/guzzle#2135]
| Q            | A
| ------------ | ---
| Bug?         | unsure
| New Feature? | no
| Version      | current

#### Actual Behavior

The Guzzle autoload config loads functions.php and not functions_include.php, which means that if you have multiple vendored versions of Guzzle in your project (WordPress + different plugins) you get fatal errors, e.g.

```
Fatal error: Cannot redeclare GuzzleHttp\json_encode() (previously declared in X/public_html/wp-content/plugins/civicrm/civicrm/vendor/guzzlehttp/guzzle/src/functions.php:322) in X/public_html/wp-content/plugins/S3-Uploads/lib/aws-sdk/GuzzleHttp/functions.php on line 322
```

#### Expected Behavior

Ideally you wouldn't get the fatal errors when two plugins are loading similar versions of Guzzle.

#### Steps to Reproduce

You could reproduce it by cloning GuzzleHttp into two different locations and including both of their `autoload.php` files.  The only problem is the function duplication, not the class duplication.

#### Possible Solutions

In [build/packager.php](https://github.com/guzzle/guzzle/blob/master/build/packager.php), autoload the `functions_include.php` versions of files instead of `functions.php`.  I'm happy to provide a pull request.

**Comment by sagikazarmark** [comment]
That indeed looks like a bug. functions_include was introduced later than the builder script. A PR would be appreciated.

On a side note: I'm not really sure why it makes sense to include different versions of Guzzle. The autoloader will only load one of them anyway, so using different versions of guzzle in the same process is actually impossible. Fixing this bug will only make the error go away, but I'd be very careful because this could cause a lot of issues.

**Comment by takkaria** [comment]
It doesn't make any sense to include different versions of Guzzle at all.  The right fix is clearly to only have one version, but I can't see any way of making that happen in my situation (a WordPress plugin plus CiviCRM, which is a WordPress plugin which can have its own plugins...).

I'll try to file a PR soon.
