### ISSUE TITLE
PHP 7.2 each() depricated

### ISSUE THREAD

**Issue by TomTheRock** [guzzle/guzzle#2174]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 6.3.3

#### Actual Behavior

Throw Warning (Depricated function)

#### Expected Behavior

no Warning

#### Steps to Reproduce

guzzlehttp/promises/src/functions.php

#### Possible Solutions

overhaul code at Line: 222, 257, 313, 346

**Comment by legoktm** [comment]
The each function in the file you're referring to is *not* the deprecated PHP each(). It's actually `GuzzleHttp\Promise\each` and is defined in the same file. While the naming is confusing, I don't see anything actionable or wrong here.

**Comment by sagikazarmark** [comment]
@TomTheRock can you please show us the warning you are referring to?

**Comment by eostis** [comment]
Here is the php 7.2 compatibility check warnings triggered by https://fr.wordpress.org/plugins/php-compatibility-checker/. The same test with PHP 7.1 is fine.

"
FILE: /guzzlehttp/promises/src/functions.php
----------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 3 WARNINGS AFFECTING 3 LINES
----------------------------------------------------------------------------------------------------------
 222 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 257 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
 313 | WARNING | Function each() is deprecated since PHP 7.2; Use a foreach loop instead
----------------------------------------------------------------------------------------------------------
"

**Comment by legoktm** [comment]
The compatibility checker you're using has a bug then, the `each()` called in that file (which isn't even this repository btw) is not the built-in `\each()` that was deprecated in PHP 7.2.

**Comment by eostis** [comment]
It's possible indeed. But other php checkers could be misleaded also.

Would it be possible to just rename the each() function to prevent any confusion?

**Comment by sagikazarmark** [comment]
`each` fits the domain nicely, so most probably there won't be any changes.

I would rather suggest reporting this issue to the maintainer of that code checker plugin.

**Comment by eostis** [comment]
Thanks. I will.

But to me, using a reserved PHP  keyword as a function name is not a good idea. One day, PHP could decide to prevent it.

**Comment by eostis** [comment]
Just for reference, here is the plugin's support ticket: https://wordpress.org/support/topic/false-positive-on-function-each/

**Comment by sagikazarmark** [comment]
It's not reserved anymore. 🙂 It's being deprecated and removed. Besides, namespaced functions provide exactly this feature: reusing function names.
