### ISSUE TITLE
Default exception handler returns invalid error code

### ISSUE THREAD

**Issue by Falseclock** [guzzle/guzzle#2183]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no

![image](https://user-images.githubusercontent.com/3299139/47775002-b460da80-dd18-11e8-933b-d7b3b3841ce9.png)

Error code should be compatible with predefined constants http://php.net/manual/en/errorfunc.constants.php

Guzzle returns HTTP Status code.

**Comment by sagikazarmark** [comment]
I'm not 100% sure that there is such rule that exception error codes can only be predefined error constants.

As per [php.net](http://php.net/manual/en/language.exceptions.extending.php):

```
<?php
class Exception extends Throwable
{
    // ...
    protected $code = 0;                        // user defined exception code
```

**Comment by Falseclock** [comment]
@sagikazarmark yes, you can define your own exception codes. That is true.
But it is applicable when you develope your own application. 

This project is not private. As well as other public projects which can handle standart exceptions. 
Let's imagine you use https://github.com/josegonzalez/php-error-handlers or this one https://github.com/thephpleague/booboo

and you never expect to get any error with code 500 or 503 or 504 etc. 

This happened to me, cause I handle only system defined errors according to bit mask from  error_reporting function

```php
	public static function saveOrPrintError($e) {
		static $errorType = [
			0                   => 'Exception',
			E_ERROR             => 'Error',
			E_WARNING           => 'Warning',
			E_PARSE             => 'Parsing Error',
			E_NOTICE            => 'Notice',
			E_CORE_ERROR        => 'Core Error',
			E_CORE_WARNING      => 'Core Warning',
			E_COMPILE_ERROR     => 'Compile Error',
			E_COMPILE_WARNING   => 'Compile Warning',
			E_USER_ERROR        => 'User Error',
			E_USER_WARNING      => 'User Warning',
			E_USER_NOTICE       => 'User Notice',
			E_STRICT            => 'Runtime Notice',
			E_DEPRECATED        => 'Deprecated',
			E_USER_DEPRECATED   => 'User Deprecated',
			E_RECOVERABLE_ERROR => 'Catchable Fatal Error'
		];

		if($e->getCode() != 0 && !in_array($e->getCode(), ErrorHandler::getBits(error_reporting()))) {
			return;
		}

	/**
	 *
	 * @param int $decimal
	 *
	 * @return array
	 */
	public static function getBits($decimal) {
		$scan = 1;
		$result = [];
		while($decimal >= $scan) {
			if($decimal & $scan)
				$result[] = $scan;
			$scan <<= 1;
		}

		return $result;
	}
}
```

**Comment by Falseclock** [comment]
it shoule be something like that, keeping original http://php.net/manual/en/errorfunc.constants.php

```php
class SomeException extends Exception
{
	/** HTTP Status Response */
	protected $status;

	public function __construct(string $message = "", $status = null) {
		$this->status= $status;

		parent::__construct($message);
	}

	public function getStatus() {
		return $this->status;
	}
```

**Comment by sagikazarmark** [comment]
>  But it is applicable when you develope your own application.

I'm failing to see why. Where is it written?

> cause I handle only system defined errors according to bit mask from error_reporting function

I still don't see how PHP error codes are related to exceptions. Error codes are for errors, not exceptions.

**Comment by Falseclock** [comment]
@sagikazarmark please, make difference.

PHP ErrorCodes are http://php.net/manual/en/errorfunc.constants.php
HTTP Status codes are  https://httpstatuses.com/ 

HTTP Status Codes ARE NOT THE SAME to ErrorCodes 

Guzzle in case of exception returns HTTP status Code in ErrorCode field

Look at this http://php.net/manual/en/class.exception.php
```php
protected int $code ;

final public mixed getCode ( void )
```

to catch Guzzle exeptions with standart and common way as written in http://php.net/manual/en/function.error-reporting.php I have to define all HTTP status codes as errors

```php
error_reporting(E_ERROR | E_WARNING | E_PARSE | E_NOTICE | 500 | 501 | 502 | 503 | 504 | 505 | etc...) ;
```

do you think is it adequate way?

**Comment by Falseclock** [comment]
@sagikazarmark if you still do not understand what do I mean I can create POC showing that in case of following PHP standarts Guzzle Exception will never be caught if error_reporting set not to E_ALL.

**Comment by guilliamxavier** [comment]
@Falseclock: Sorry but you are mixing two orthogonal things: *error levels* and *exception codes* are independent, because *errors* and *exceptions* are two distinct things (note: "errors" here means PHP errors like fatal errors, warnings, notices... not the `Error` class introduced in PHP 7):

- errors are triggered, can be silenced with `@` (or `error_reporting()`), and non-fatal run-time errors can be user-handled via `set_error_handler()` (and the program execution can be resumed);
- exceptions are thrown, can be caught with `try`-`catch` blocks, and uncaught exceptions can be user-handled via `set_exception_handler()` (but the program execution cannot be resumed).

An error level is one of the `E_`* constants (other than `E_ALL` which is the union of all levels), whereas an exception code can be anything relevant to the domain (even a string like "HY000" for PDOException) and has nothing to do with the error_reporting level. You can play with https://3v4l.org/JsvUO to see that both are unrelated (even if by default an uncaught exception triggers a fatal error, and even if some frameworks add a global error handler that for some error levels throws an exception).
