### ISSUE TITLE
cookie file is not saved by using CURLOPT_COOKIEFILE and CURLOPT_COOKIEJAR

### ISSUE THREAD

**Issue by onemans-battle** [guzzle/guzzle#2238]
**Guzzle version(s) affected**: 
6.3.3

**Description**  

I want to save the cookie file with Netscape HTTP Cookie File format not json format. So I use the CURLOPT_COOKIEFILE and CURLOPT_COOKIEJAR option to save cookie. But Guzzle does not work and I've seen it work #382. I have tried curl directly and it worked.

**How to reproduce**  

using Guzzle: like #382

```php
$cookie='path\to\cookies\domain.com';
$opt=['curl'=>[
                CURLOPT_COOKIEFILE=>$cookie,
                CURLOPT_COOKIEJAR=> $cookie,
            ]];
$c=new \GuzzleHttp\Client();//set ['cookies'=>true] is the same
$res=$c->request('get','www.domain.com',[
            'curl'=>[
                CURLOPT_COOKIEFILE=>$cookie,
                CURLOPT_COOKIEJAR=> $cookie,
            ]
        ]);
$res->getBody();

//I also tried
$c=new \GuzzleHttp\Client([
            'curl'=>[
                CURLOPT_COOKIEFILE=>$cookie,
                CURLOPT_COOKIEJAR=> $cookie,
            ]]);
$res=$c->get('www.domain.com');
```

using curl and it work:
```php
$cookie='path\to\cookies\domain.com';
$curl=curl_init('www.domain.com');
curl_setopt($curl,CURLOPT_COOKIEFILE,$cookie);
curl_setopt($curl,CURLOPT_COOKIEJAR,$cookie);
curl_exec($curl);
```

**Possible Solution**  

Does the new version remove this feature?

**Additional context**

**Comment by jbilbo** [comment]
any update on this?

**Comment by gmponos** [comment]
I spent a lot of hours yesterday trying to figure this out.

Let's talk about the two options separately 

**CURLOPT_COOKIEFILE**

This option does seem to work. What I have as a reproducer:

`jar.txt`

```
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

httpbin.org	FALSE	/	FALSE	0	mycookie	value
```

index.php

```
<?php

require_once 'vendor/autoload.php';

$cookieFile = __DIR__ . '/jar.txt';
$cookieFileSave = __DIR__ . '/save.txt';

$c = new \GuzzleHttp\Client();
$res = $c->request('get', 'https://httpbin.org/cookies', [
    'curl' => [
        CURLOPT_COOKIEFILE => $cookieFile,
        CURLOPT_COOKIEJAR => $cookieFileSave,
    ]
]);
echo $res->getBody()->__toString();
```

ouput:

```
php index.php 
{
  "cookies": {
    "mycookie": "value"
  }
}
```

If you have different results please provide a reproducer with similar data like above.. meaning the content of your cookie, a website that we can actual reproduce it etc etc..


**CURLOPT_COOKIEJAR**

This problem seems to be more complicated. According to the documentation of PHP https://www.php.net/manual/en/function.curl-setopt.php 

> The name of a file to save all internal cookies to when the handle is closed, e.g. after a call to curl_close. 

The file is saved when `curl_close` is called or when the class is destructed. The problem is that on Guzzle we [do a curl_reset of the curl handler](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L84). I am not sure if PHP should write the file on curl reset or if it is something that should be handled on Guzzle.

Never the less I am open to ideas for fixing this.

**Comment by onemans-battle** [comment]
Thank you for your reply. I'm sorry to have taken up your time to solve this problem.
Now I think the josn format is good enough. The original format is not very friendly.
In addition, I can easily convert json to another format if I need.
