### ISSUE TITLE
GET request with PFX certificate

### ISSUE THREAD

**Issue by siddiqlm** [guzzle/guzzle#2261]
**Guzzle version(s) affected**: 6.3.3  
**cURL**: 7.560  
**PHP**: 7.1.13

**Description**  
I want to send a GET request with pfx certificate using Laravle Guzzle. I tried to send a request as explained in [this link](http://docs.guzzlephp.org/en/stable/request-options.html#cert) but with PFX certificate. But I got "cURL Error 58: Could not load PEM certificate". 

How to send a GET request with PFX certificate using Laravel Guzzle? 

**How to reproduce**  
1. Save a PFX certificate file in your server
2. Send request using Guzzle like `$client->request('GET', '/', ['cert' => ['/path/server.pfx', 'password']]);`

**Additional context**  
I tried to convert PFX to PEM and tried with the same code. But this time I got "cURL Error 60: SSL Certificate problem: unable to get local issuer certificate"

**Comment by zshbsm** [comment]
i have the same issue.

**Comment by brbrowning21** [comment]
You were actually headed in the right direction by converting it to PEM, which is the format that Guzzle accepts.

The "cURL Error 60: SSL Certificate problem: unable to get local issuer certificate" was caused by a separate issue (yet still related to certificates): The website you are requesting either doesn't have a certificate or the website's certificate is not trusted by your computer. If you totally trust the website, you can set the `verify` request option to `false` (not recommended, unless you control the server). Otherwise, set `verify` to the path of a file of a trusted certificate bundle. See the docs for the [verify param](http://docs.guzzlephp.org/en/stable/request-options.html#verify).
