### ISSUE TITLE
New Release on version 6?

### ISSUE THREAD

**Issue by eusonlito** [guzzle/guzzle#2306]
Hello! what about to launch a new release to version 6 with current commits on master?

Last release is more than one year ago (april 2018) and there are about 100 commits more on master.

Thanks!

**Comment by sagikazarmark** [comment]
Hi there,

There will be a new release in the near future, unfortunately time is a constraint. :(

**Comment by eusonlito** [comment]
:muscle: :muscle:

**Comment by j0k3r** [comment]
@sagikazarmark do you need help for that new release?

**Comment by it-can** [comment]
Any news on this?

**Comment by awd-studio** [comment]
Up. 
(Need some feature from master)

**Comment by it-can** [comment]
@sagikazarmark can we expect a new release soon?

**Comment by sagikazarmark** [comment]
Hi,

terribly sorry for the delays. I will review the current state of master to see if we can speed things up.

**Comment by gmponos** [comment]
To be fair.. 

> Maybe by creating an issue with change logs and make sure we don't have any nasty BC breaks.

that's also true mentioned by @Nyholm 

And also myself lately I am out of any spare time.

**Comment by Nyholm** [comment]
I will focus the next few hours to make sure @gmponos and @sagikazarmark can be confident with releasing 6.4. 

We should also plan a 6.5 soon.

**Comment by sagikazarmark** [comment]
There are many things to consider in OSS maintenance. During the last year, most of my extra energy was spent on answering support tickets, explaining people that 404 is not a Guzzle issue.

If I could spend that time on reviewing PRs, I think things would be much faster.

As for more frequent releases: I'm all for it, but we need a plan (eg. minor release every quarter, patch release when there are at least 2-3 fixes in the queue).

The third thing on my mind: currently we are struggling with maintaining 6.x and preparing 7.x. We also need to balance that effort, but 7.x is also in the queue for a loooooong time. There are already some PRs, but I'm not completely happy with them. We need a plan on this front as well, so the community can contribute.

Ultimately, I think the key is to make the development of Guzzle much more open, so that the maintainers can focus on the most important issues.

**Comment by Nyholm** [comment]
I would be super happy if all of us waiting for 6.4.0 would do (all or some of) these things: 

A) Review #2374 (Change log)
B) Review the diff since [last release](https://github.com/guzzle/guzzle/compare/6.3.3...master)
C) Test dev-master to make sure it works in your project

If you done at lease one of the above, please write here and tell us the result. That will ease the stress of creating a new tag with a bug in it.
