### ISSUE TITLE
Can i read one line at a time with streams?

### ISSUE THREAD

**Issue by omatamix** [guzzle/guzzle#2406]
Hi my name is Nick, i am wondering is there a way to read one line at time when it comes to streams?

```php
$stream = $this->api->getStream();
while (!$stream->eof()) {
    echo $stream->read(1024);
}
```

The variable `stream` is the same as the `body` variable in your example, same results.

```php
$body = $response->getBody();
while (!$body->eof()) {
    echo $body->read(1024);
}
```

Now i was wondering is there a method or something that will just read the next line, for example.

```php
$body = $response->getBody();
while (!$body->eof()) {
    echo $body->readLine();
}
```

I saw something about it in earlier versions is there a new way of doing this?

**Comment by sagikazarmark** [comment]
Guzzle uses PSR-7 for messaging.

Unfortunately the stream interface does not expose such functionality:
https://www.php-fig.org/psr/psr-7/#34-psrhttpmessagestreaminterface

It should be easy to come up with a few lines of code though that can split buffered reads. But it can't be part of the stream implementation, because we rely on PSR-7 interfaces only.

**Comment by omatamix** [comment]
Thanks for the reply, i was able to find a work around.

**Comment by ahosker** [comment]
Care to share @omatamix ?

**Comment by Sacerdoss** [comment]
If anyone stumbles upon this question today, you can use the following:

```php
\GuzzleHttp\Psr7\Utils::readLine()
```
