### ISSUE TITLE
Problem with form_params encoding

### ISSUE THREAD

**Issue by cccaballero** [guzzle/guzzle#2487]
I am trying to replicate this working curl request:

    curl -X POST -k -H 'Authorization: Basic SOME_CODE_HERE' -i 'https://apisandbox.enzona.net/token' --data grant_type=client_credentials --data scope=enzona_business_payment+enzona_business_qr

I am doing it in this way:

```
        $res = $client->request('POST', $this->host . $this->accessTokenRoute, [
            'auth' => [$customer_key, $customer_secret],
            'form_params' => [
                'scope' => "enzona_business_payment+enzona_business_qr",
                'grant_type' => 'client_credentials',
            ],
        ]);
```

But I am getting issues because the `scope` param is being encoded (the issue is with the `+` symbol) and the server doesn't  recognize my scopes. How can I make it work?

**Comment by gmponos** [comment]
Hello there..

When you use form_params of guzzle you send an application/x-www-form-urlencoded POST request.

Check http://docs.guzzlephp.org/en/latest/request-options.html#form-params

So the curl Request you wrote there is not equivalent to that. 

Generated from postman:

```
curl --location --request POST 'https://httpbin.org/post' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'email=test+test@test.com'
```

If you still want to use form params the problem is that your server is not decoding hte values.. Otherwise use the body option and create the body.
