### ISSUE TITLE
[RFC] Deprecate getConfig

### ISSUE THREAD

**Issue by GrahamCampbell** [guzzle/guzzle#2514]
I feel like the client configuration should be immutable, and should not be exposed to the outside, either to be read, or to be changed. Should we mark `getConfig` on the client interface as deprecated in 7.x, and remove it in 8.0.0?

**Comment by alexeyshockov** [comment]
Could you explain more? I agree that "the client configuration should be immutable", but don't see any reason why "should not be exposed to the outside".

To me the real issue with immutability here is that the handler can be modified, because usually it's a `HandlerStack` object, and it's itself mutable (allows adding/removing middlewares to it). IMO we should freeze it somehow (or not expose it) instead of closing the whole configuration.

Also there is a [`cookies` option](http://docs.guzzlephp.org/en/stable/request-options.html#cookies), for example, that can be set to a cookie jar globally (for a client object) and accessed later via `$httpClient->getConfig('cookies')->clear();`. But if `getConfig()` is removed, there will be no way to access it (that is bad IMO).

**Comment by gmponos** [comment]
I have also the feeling that this function is heavily used and will offer many headaches to developers by removing it.

For instance check.. 
https://github.com/googleads/googleads-php-lib/blob/master/src/Google/AdsApi/Common/AdsGuzzleHttpClientFactory.php#L69

**Comment by sagikazarmark** [comment]
The config is an internal detail, that's sufficient reason for me not to expose it.

Whether something should be config or not is a different question.

If the client needs to provide access to cookies it should be a dedicated method, but not exposing it would also work for me: if you need access to cookies, pass around the cookie jar.

**Comment by gmponos** [comment]
@sagikazarmark I don't disagree and I want it also removed.. My only concern is the overhead this might cause.. 

PhpUnit started first by adding annotation.. then on next major it added the trigger error deprecation notice.. and then the functions were removed... 

If we followed same path.. this would mean on version 9... which seems a long way until then.. 

Maybe instead of that we could add the annotation on 7.1 and add the notice on 7.2 then remove it on 8.

**Comment by sagikazarmark** [comment]
That's the original proposal:

> Should we mark getConfig on the client interface as deprecated in 7.x, and remove it in 8.0.0?

I added 7.1 milestone to the PRs, but not to the issue.

**Comment by ondrejcech** [comment]
> I feel like the client configuration should be immutable, and should not be exposed to the outside, either to be read, or to be changed. Should we mark `getConfig` on the client interface as deprecated in 7.x, and remove it in 8.0.0?

@GrahamCampbell by removing this method you made it impossible to access config options such as timeout_* which is very useful in exceptions. E.g. when requests failed and you want to know the timeout settings for the given request. Do you have any workaround in mind?

**Comment by Nyholm** [comment]
Could you elaborate why it is useful?

Do you mean you want to tell the user that timeout of 5s seconds was too short? The user is the one that configured the timeout, if they see a timeout exception they already know what their current timeout is.

**Comment by ondrejcech** [comment]
We're using a scenario where the timeout is increased for every retry in exponential backoff and if this fails I want to know the timeout that was used. Even though I'm kinda setting the value, I don't know the value for a failed requests. 

The same applies to a pool of asynchronous requests that can have different timeouts. Sure, I can pass around some extra information about the request and its timeout but the getConfig method was really convenient way how to get to the values when handling exceptions.

**Comment by Nyholm** [comment]
Okey. So you have implemented your own `RetryMiddleware`. Cool. 

I still dont think it is a good idea for an immutable service to expose its configuration. It is internal details of the service. As the service creator, you already know this information. 

I see that you already know your workaround.

**Comment by ondrejcech** [comment]
I get your point about `RetryMiddleware` and I agree. Thanks for you time.

**Comment by VBobCat** [comment]
I have a question. Please consider a client instance initialized with `['cookies'=>true]`.

I am using `$guzzleClient->getConfig('cookies')` to retrieve this cookiejar because I need to check whether a given cookie was set. How will I get this object after `getConfig` is removed?

Thank you very much.

**Comment by CatalinH** [comment]
For example I use getConfig to have a smooth generic way to increase the length of http exception message from 120 without the need to construct the whole HandlerStack, but I guess this seems a hackish way

**Comment by Atomzwieback** [comment]
if `getConfig()` is getting removed how we can extend a given config after client initalization?

**Comment by kerwanp** [comment]
In our case we have a really simple use case.

We have a service autowired with a `Guzzle\Client` that has `form_params => ['username' => 'xxxx', 'password' => 'xxxx']`.
As we still want to append new `form_params` we merge them with the client config:

```php
        $response = $this->httpClient->post('', [
            'form_params' => [
                'action' => 'shorturl',
                'url' => $url,
                'keyword' => $keyword,
                'format' => 'simple',
            ] + $this->httpClient->getConfig('form_params') // Merging with 'form_params' already defined in the client (username & password)
        ]);
```

**Comment by ivanrey** [comment]
The last two comments seem very important to me. How can you create a new Client based on another Client, for example to add more parameters or new handlers, without knowing which things it had before. One key aspect of immutability is that if you want you can copy and append, but without the getConfig method its really hard to "append" new functionality to an already instantiated Client
