### ISSUE TITLE
Upload content with PUT/multipart fails

### ISSUE THREAD

**Issue by prodigy7** [guzzle/guzzle#2569]
I spend some hours but don't really find a solution for my problem. Current I build a array like this:
```
array:7 [▼
  0 => array:2 [▼
    "name" => "urls[0]"
    "contents" => "http://www.test.com"
  ]
  1 => array:2 [▼
    "name" => "type"
    "contents" => "journalist"
  ]
  2 => array:2 [▼
    "name" => "hasFile"
    "contents" => "1"
  ]
  3 => array:2 [▼
    "name" => "hasOnline"
    "contents" => "1"
  ]
  4 => array:3 [▼
    "contents" => stream resource @49 }
    "filename" => "Logo_1_final.jpg"
    "name" => "file"
  ]
  5 => array:2 [▼
    "name" => "fileRemove"
    "contents" => false
  ]
  6 => array:2 [▼
    "name" => "status"
    "contents" => 1
  ]
]
```
This array I send with a PUT request to laravel instance:
```
$apiResponse = $client->request('PUT', '/url', [
   'multipart' => $multipartRequest
]);
```
When I catch the quest, it is complete empty. When I change PUT to POST, I can grab the data with ``request()``.

Whats wrong?

**Comment by alexeyshockov** [comment]
> When I catch the quest, it is complete empty. When I change PUT to POST, I can grab the data with request().

Looks like Guzzle itself works fine, you should check your Laravel app. Does it support PUT? What does "it is complete empty" mean, what is the response status code? It could be completely normal, depends, again, on your Laravel backend logic.

I'm closing it for now, feel free to reopen with more info or ask [on StackOverflow](https://stackoverflow.com/questions/tagged/guzzle) (because it doesn't look like a Guzzle issue, but more like a general question).
