### ISSUE TITLE
No support for Request Options in Psr\Http\Client\ClientInterface::sendRequest

### ISSUE THREAD

**Issue by bshaffer** [guzzle/guzzle#2592]
**Guzzle version(s) affected**: 7.0.0-beta
**PHP version**: n/a
**cURL version**: n/a

**Description**  
We want to accept PSR-18 clients for making HTTP requests, but we have noticed that the `sendRequest` method signature does not accept request `$options`. For things such as `timeout`, `proxy`, `debug`, `verify`, there is no way for us to supply defaults on a per-request basis.

For instance, we cannot set a higher timeout for certain API calls.
For instance, we cannot set `debug` on clients in a debug environment.
..etc 

So our inclination is to support Guzzle6 and Guzzle7 specifically, and wrap with our own Interface, to ensure consistency and support request options and add async. When a PSR-18 client is passed in, our request options will simply be ignored. Is this WAD?

Thank you!

**Comment by Nyholm** [comment]
That is correct. As a library author, it is out of our concern if we should verify TLS certificate or not. We should also not care if the client is in a "debug mode" or using a proxy. It is up to the application user to configure their HTTP clients and in the way they see fit, and then just give us the client object. 

As a library author, we define **what** is sent by creating a PSR-7 request. **How** that is sent is nothing we need to know. 

You could claim that you need some super specific guzzle settings etc etc. That is fine, then PSR-18 is not for you. The reason why request options is not part of PSR-18 is because it is impossible to define that list. It is either too short, too long, too granular, not flexible enough and will soon be out-of-date. If you define 20 different options, then lightweight clients like Buzz will not be able to implement it.

**Comment by GrahamCampbell** [comment]
I agree with @Nyholm.
