### ISSUE TITLE
[Question]Is there anyway to detect and retry when connection reset by peer?

### ISSUE THREAD

**Issue by allgrowsm** [guzzle/guzzle#2733]
Hello there,

I have question about if we can retry when connection reset by peer.

One of our server resets the connection sometime because of system failure.

So, I want to sleep for few minutes and retry.

Do you have any suggestion for this?

Regards,

**Comment by GrahamCampbell** [comment]
Yes. Guzzle's retry middleware.

**Comment by allgrowsm** [comment]
@GrahamCampbell 
Thanks for that.

I created following, but, it dose not detect  connection reset by peer.

https://github.com/msaus/PHP/blob/master/Library/guzzelRetryClient.php

Do you have any suggestion for this source code?

**Comment by GrahamCampbell** [comment]
You can just look at the exception message, or just retry for any kind of transport exception.

**Comment by GrahamCampbell** [comment]
> So, I want to sleep for few minutes and retry.

If you want to sleep for a few **minutes**, you should probably take your retry logic outside of Guzzle, and come back to what you were doing later, via a queue job or something.

**Comment by allgrowsm** [comment]
@GrahamCampbell 
Thanks!
Possibly, I may have to catch the exception in retryDecider?

**Comment by fredericgboutin-yapla** [comment]
The thing that seems odd to me is that the "Connection reset by peer" curl error is reported as a `RequestException` instead of a `ConnectionException`.

Why does it matter? Because I'm using this middleware - https://github.com/caseyamcl/guzzle_retry_middleware - and [it rightfully only look for `ConnectionException`](https://github.com/caseyamcl/guzzle_retry_middleware/blob/319829956ad61be3f48fba8f79e789b92538e56f/src/GuzzleRetryMiddleware.php#L213).
