### ISSUE TITLE
How to use CURLOPT_ERRORBUFFER

### ISSUE THREAD

**Issue by Sarveshmrao** [guzzle/guzzle#2749]
Please let me know how to use https://curl.haxx.se/libcurl/c/CURLOPT_ERRORBUFFER.html this via guzzle.

**Comment by mfn** [comment]
What you're asking for as an internal implementation in php => if you call `curl_error()`, it works because "under the hood" it was already using `CURLOPT_ERRORBUFFER` =>https://github.com/php/php-src/blob/f982038fb676089b594b2a94f5c7edb14bf212b5/ext/curl/interface.c#L1825

If you ask about Guzzle and `curl_error` => https://github.com/guzzle/guzzle/blob/33ddb580d0d88242fa9d597b4715f5f89c5e56a1/src/Handler/CurlFactory.php#L153

I'd like to point out that, without further context, it's hard to give you a better answer.

HTH

**Comment by Sarveshmrao** [comment]
Sorry for not elaborating. 
I use an extension in my php app or website which uses guzzle. It gets curl error 35. When I checked the website it mentioned in the error it showed to use `CURLOPT_ERRORBUFFER` to get human readable error.

I'm not very much experienced using guzzle.
So how do I use `CURLOPT_ERRORBUFFER` only through guzzle. Also is there any documentation for that. As I was not able to find any in guzzle documentation. 
Thanks!

**Comment by Sarveshmrao** [comment]
Can anyone help me?

My question is "How do I use `CURLOPT_ERRORBUFFER`?"

**Comment by Sarveshmrao** [comment]
You guys don't help!
