### ISSUE TITLE
Status code must be an integer value between 1xx and 5xx.

### ISSUE THREAD

**Issue by cappadaan** [guzzle/guzzle#2751]
Guzzle version(s) affected: 7.0.1
PHP version: 7.4.9
cURL version: 7.64.1

Lately I run into this randomly fatal error

"PHP Fatal error:  Uncaught InvalidArgumentException: Status code must be an integer value between 1xx and 5xx. "

The error message is not clear at all and causes confusion. Does the URL gives me a invalid status header? Which call causes this error and why? Is there an option to catch this error, because so far I am not able to.

I think it is related to issue: https://github.com/guzzle/guzzle/issues/2534
Is this a known problem?

**Comment by kekodmc** [comment]
\vendor\guzzlehttp\psr7\src\Response.php   151

**Comment by strarsis** [comment]
Composer-based patch: https://github.com/spatie/crawler/issues/271#issuecomment-642645685
However, I had trouble applying that patch to my project.

**Comment by Nyholm** [comment]
The status code in the HTTP response must be between 100 and 599. 

This is related to Guzzle/psr7.

**Comment by williamjulianvicary** [comment]
@strarsis This issue is different to #2534 which was related to this exception causing issues when encountering it with a Pool - the PR that was just merged fixes the issues that caused the Pool to misbehave, but does not resolve the issue of not being able to review the raw response that triggered the PSR7 response InvalidArgumentException.

This issue is still relevant in my opinion (https://github.com/guzzle/psr7/issues/349) and I'll comment over there.
