### ISSUE TITLE
Call to undefined function GuzzleHttp\\Psr7\\stream_for()

### ISSUE THREAD

**Issue by edtownend** [guzzle/guzzle#2824]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 7.4.12
**cURL version**: 7.73.0

**Description**  
It looks like the recent switch to static util functions in 7.2.0 (https://github.com/guzzle/guzzle/pull/2712) missed a call in
https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L400

**How to reproduce**  
The request is created deep within another library I'm using so I'm not sure how to make a minimal reproduction.

**Possible Solution** 
Within GuzzleHttp/Handler/CurlFactory.php, change:
```php
if (!\is_string($sink)) {
    $sink = \GuzzleHttp\Psr7\stream_for($sink);
} elseif (!\is_dir(\dirname($sink))) {
```
to:
```php
if (!\is_string($sink)) {
    $sink = \GuzzleHttp\Psr7\Utils::streamFor();
} elseif (!\is_dir(\dirname($sink))) {
```
I'm not sure what the purpose of the $sink parameter is and how it would convert to the new syntax, otherwise I'd make a pull request.

Thanks!

**Comment by GrahamCampbell** [comment]
That PR didn't miss it. That code was added afterwards: https://github.com/guzzle/guzzle/commit/d48af55e18e40e422cc27ddc35fe081135bf6a9a. I think we need to add the phpstan deprecation plugin @Nyholm so that class of error can't happen.

**Comment by codeurient** [comment]
package is  classic-o / nova-media-library

I have the same problem.

I updated all also it is not working. this problem only when I want to add img. with video or pdf doc file is not problem. 
call to undefined function GuzzleHttp\Psr7\stream_for()

so who can help me ?

**Comment by Konali** [comment]
There is a problem in the library Intervention : http://image.intervention.io/getting_started/releasenotes since the release of 14/07/2021 if you upgraded to last version 2.6 

It's still using the old way to call the function : 

replace in intervention\image\src\Intervention\Image\Commands\StreamCommand.php 

`    $this->setOutput(\GuzzleHttp\Psr7\stream_for(`

BY

`         $this->setOutput(\GuzzleHttp\Psr7\Utils::streamFor( `

You can update both package updated with : 

        "guzzlehttp/guzzle": "^7.3.0",
        "intervention/image": "^2.6",

**Comment by codeurient** [comment]
I changed the way of guzzlehttp on file composer.lock as a 7.2 and some
little different things after I did composer update and this error was
canceled...

The first I did like this  "guzzlehttp/guzzle": "^7.2.0", on composer.json
and composer  update but it also updated to 7.3.0. After my friend told me
not to need to write composer update, I need to write composer install and
it will be saved as a 7.2.0... I still did not try this way because I was
so busy. :) after I will try this too

**Comment by JPeterson2015** [comment]
Updating to latests php version worked for me. Was on 7.3 now using 8.0

**Comment by codeurient** [comment]
Awesome, thanks!

**Comment by ndr3x** [comment]
I found a simpler way to fix this issue. Just forcing the version 7.2.0 + allowing downgrades

` composer require guzzlehttp/guzzle:~7.2.0 -w`

**Comment by codeurient** [comment]
actually, the problem was in laravel nova version. You can buy only one
license. But me used one license for two time. Because I got this error
every time.
After I copied file composer.lock form first project to second and the
error is gone. But also it is not true way to fix this problem because it
was illegal to use for two time one license. 😂

**Comment by koostamas** [comment]
> 

I have to use PHP 7.3, I was using laravel-notification-channels/fcm and Guzzle 7.4 got installed. Downgrading to 7.2 solved the problem for me.

**Comment by codeurient** [comment]
Glad to hear it!

**Comment by GrahamCampbell** [comment]
Guzzle 7.4 works on PHP 7.3, too.

**Comment by codeurient** [comment]
Thanks, I'll check it out.

чт, 10 мар. 2022 г., 0:59 Graham Campbell ***@***.***>:

**Comment by oh-huohou** [comment]
https://docs.aws.amazon.com/aws-sdk-php/v3/api/function-GuzzleHttp.Psr7.stream_for.html

**Comment by Lancom-BoundaryBend** [comment]
> > `composer require guzzlehttp/guzzle:~7.2.0 -w`

Thanks this solve the issue for me

**Comment by GrahamCampbell** [comment]
Do not attempt to install Guzzle 7.2.x. It has multiple security vulnerabilities. I have removed harmful comments suggesting options that are not secure. I am going to lock this to prevent more disinformation. The **ONLY** version of Guzzle that are safe are 6.5.8 or any later 6.x version, and 7.4.5 or any later 7.x version. Guzzle 6 will be EOL later this year, so everyone should be looking to upgrade to 7.4.5 or later.
