### ISSUE TITLE
Notice: Undefined offset: 1 in /script/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 453

### ISSUE THREAD

**Issue by kaufmannmax** [guzzle/guzzle#2827]
**Guzzle version(s) affected**: 7.2.0
**PHP version**: 7.4.7 (hint: `php --version`)
**cURL version**: x.y.z (hint: `php -i | grep cURL`)

**Description**  
A Notice is shown if using a *.pem certificate, and no password is added
Notice: Undefined offset: 1 in /script/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 453

**How to reproduce**  
$client = new Client();
            $res = $client->request(
                'POST', $this->fullendpointurl,
                [
                    'cert' => [
                        $this->endpoint->getCertFilepath()
                    ],
                    'json' => (array)$content
                ]
            );

**Possible Solution**  
Maybe simply checking availability of the parmeter (isset or something?) in CurlFactory line 453 helps?

Temporary workaround for me was adding ANY password
$client = new Client();
            $res = $client->request(
                'POST', $this->fullendpointurl,
                [
                    'cert' => [
                        $this->endpoint->getCertFilepath(),
                        ''
                    ],
                    'json' => (array)$content
                ]
            );

**Additional context**

**Comment by mephlaren** [comment]
Sorry for formatting, i've been browsing github from my phone. 

How come this has not received any attention?

As far as I see, this could be fixed by a ternary operator in the factory classfile, since it only expects 2 params ( one being the pwd. ) 

if (\is_array($cert)) {
                $conf[\CURLOPT_SSLCERTPASSWD] = sizeof($cert) > 1 ? $cert[0] : '';
                $cert = $cert[0];
}

instead of 

if (\is_array($cert)) {
                $conf[\CURLOPT_SSLCERTPASSWD] = $cert[1];
                $cert = $cert[0];
}

Are there any security or implementational concerns over this method? I just checked the cycle from instantiating a Client object until arriving at the factory object via the implemented calls.￼

**Comment by kaufmannmax** [comment]
Yes, this could work
