### ISSUE TITLE
Timeout Exceeding Exception

### ISSUE THREAD

**Issue by mertingen** [guzzle/guzzle#2932]
**Description**
I'd like to get an exception from Guzzle if I give a timeout parameter for the client request. I couldn't find getting an exception for timeout exceeding. 

**Example**
I found a solution like the following but it really bothers me.
```
} catch (RequestException $e) {
    if (strpos($e->getMessage(), 'timed out after') !== false) {
        //timeout is exceeed.
    }
}
```

There is another example but wouldn't it catch other exceptions in this example? I'd like to throw only the timeout exception, not other problems.

```
} catch(\GuzzleHttp\Exception\GuzzleException $e) {
  // Handle excpetion
}
```

However, I'd like to write code like the following, if it's ok.
```
} catch (TimeoutException $e) {
     //timeout is exceeed.
}
```

**Comment by strictboss** [comment]
Hi @mertingen! As i know from my practice, you can use this:
`GuzzleHttp\Exception\ConnectException`.

The exception will raise if `connect_timeout` or `timeout` exceed.


But i really need to distinguish these two cases, because if `connect_timeout` exceed - request was not send (TCP connection was not establish during certain time), but if `timeout` exceeded - request was actually send and i have just did not wait for all response! And in both cases i get the same exception (`GuzzleHttp\Exception\ConnectException`) with the same exception instance code (0) with the same message of error. This is really important thing and there is a very big difference between these two cases.

**Comment by mertingen** [comment]
hi @strictboss ,

Thanks for the information but I need to distinguish these different cases. It would be helpful for me. As you said, the exact exception provides exact scneriao. The string contains truly ugly to understand the scenario. As I see, you created an issue regarding this case, thank you. I'll follow up on it.

**Comment by strictboss** [comment]
> hi @strictboss ,
> 
> Thanks for the information but I need to distinguish these different cases. It would be helpful for me. As you said, the exact exception provides exact scneriao. The string contains truly ugly to understand the scenario. As I see, you created an issue regarding this case, thank you. I'll follow up on it.

Our common pain, bro!😅

**Comment by mertingen** [comment]
#2933 related issue.

**Comment by milanchheda** [comment]
I am not sure if my case is similar, but I need to handle `timeout` exception too. Here is the code:

```
$responses = Http::pool(fn (Pool $pool) =>
            $queriesToExecute->map(
                fn ($query, $key) =>
                $pool->as($key)->timeout(5)->post('http://localhost:3000/', [
                    'headers' => $header,
                    'q' => $query
                ])
            ));
```

Basically, if the connection is timeout in 5 seconds then I need to catch that exception and show some message on the UI. Also, I am using `pool` because we want to get response for concurrent requests instead of hitting each one individually.
