### ISSUE TITLE
Guzzle Latest Version 7 and 7.2 Headers are not set 

### ISSUE THREAD

**Issue by yobotn** [guzzle/guzzle#2981]
**Guzzle version(s) affected**: 7.0 and 7.2
**PHP version**: 7.4.9
**cURL version**:  7.70.0 

I am using a pool,

```
// I used 'array()' as an example

yield new Request('POST', $uri, [

  'headers' => [
	  'Content-Length' => strlen(json_encode(array()))
  ],
  
  'allow_redirects' => [
	  'max'             => 10,
	  'strict'          => false
  ],
  
  // used this
  'body'=> json_encode(array())
  // or this 
  'json'=> array()

]);
```

content-length never been set

I also wanted to set **tokenId** didn't work unless I put it like this

```
	$client = new Client([
		'verify' => false,
	
		'timeout' => 4,

		'debug' => fopen('log.log', 'w'),

		'headers'=>[
			'Content-Type'     => 'application/json',
			'tokenId' => '7feb3728-1243-4704-90d0-530bc9a004f4'
		]

	]);
```

I found using Guzzle is furstrating so I tried Unirest and workd like a charm from first try.

**Comment by ossycodes** [comment]
@yobotn same here, experienced this bug yesterday and it was it took a lot of time before realizing.

**Comment by Nyholm** [comment]
Could you please provide a reproducer script? Or maybe even a test case?

**Comment by xnan-dev** [comment]
Hello people, 

I made a simple test against Guzzle 7 and 7.2: 
* Guzzle 7.0
     * headers Content-length and Cache-control are ignored when put in headers key array. 
 * Guzzle 7.2
     * headers Content-length gets ignored while Cache-control is sent when put in headers key array.

(It seems likely that the server ignored the Content-length header for some reason)

As a Server , I used an Apache 2.4

Regards, xnan-dev.

**Comment by xnan-dev** [comment]
* It seems to work perfectly well in Guzzle version 7.2 according to the following manual test code:

`require 'vendor/autoload.php';


$client = new GuzzleHttp\Client(
		['base_uri' => 'http://localhost:8080',
			'headers'=>[
			'Content-Length' => 1000 , 			
			'x-test'=>"ok",
			"my-header"=>"ok2"]
 		]);

$response = $client->request('GET', 'index.php');

$body = $response->getBody();

echo "response:$body";
`

node.js server for test purposes: 
`var http = require('http');

http.createServer(function (req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});
  //res.end('Hello World!');
  res.end(JSON.stringify(req.headers));
}).listen(8080);`

* This is the node.js server response, showing that the headers are correctly received:
`response:{"host":"localhost:8080","content-length":"1000","x-test":"ok","my-header":"ok2","user-agent":"GuzzleHttp/7"}
`

* Node JS version: 
[node-v16.15.0-x64.msi](https://nodejs.org/dist/v16.15.0/node-v16.15.0-x64.msi)

* Guzzle version: 
7.2.0.0

**Comment by xnan-dev** [comment]
Hello [yobotn](https://github.com/yobotn) ,
Regarding your test code for sending the tokenid, I tested it in Guzzle 7.2 against a NodeJs server instance and I got the headers correctly send according to the server's  response: 

`response:{"host":"localhost:8080","content-type":"application/json","tokenid":"7feb3728-1243-4704-90d0-530bc9a004f4","user-agent":"GuzzleHttp/7"}
`
Regards, xnan-dev

**Comment by xnan-dev** [comment]
Regarding the usage of Request object as follow, the bug is resproduced, sent headers doesn't contains the key 'Content-length', 
```

$r=new \GuzzleHttp\Psr7\Request('GET', $uri, [

  'headers' => [
  		'Cache-control' => 'no-cache'
	  'Content-Length' => strlen(json_encode(array()))
  ],
  
  'allow_redirects' => [
	  'max'             => 10,
	  'strict'          => false
  ],
  
  // used this
  'body'=> json_encode(array())
  // or this 
  //'json'=> array()

]);

```

following is the node.js server response as before:

{"host":"localhost:8080","connection":"keep-alive","pragma":"no-cache","cache-control":"no-cache","sec-ch-ua":"\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"101\", \"Google Chrome\";v=\"101\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Windows\"","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","accept-encoding":"gzip, deflate, br","accept-language":"es-ES,es;q=0.9","cookie":"PHPSESSID=4380bqd0g4f20kvhqb6saocsaf"}

**Comment by xnan-dev** [comment]
**Mistery solved guys!**

The sample code for sending the 'Content-length' header is incorrectly using the headers argument of  \GuzzleHttp\Psr7\Request , the constructor call second argument is assigned ti ["headers"=>[....]]
instead of just [,..]

The confusion surges likely from the fact that Client class sends the header as a sub-array with key "headers" while Request class sends just the array (no header key). 

Following is the correct sample code in PHP:
```
$client = new \GuzzleHttp\Client([
	'verify' => false,
	'timeout' => 4,
	'debug' => fopen('log.log', 'w')
]);

$r=new \GuzzleHttp\Psr7\Request('GET',"http://localhost:8080",
	
	[
		'Cache-control' => 'no-cache',
		'Content-length' =>2
	]
);

$promise = $client->sendAsync($r)->then(function ($response) {
    echo 'I completed! ' . $response->getBody();
});

$promise->wait();

```
And here is the NodeJs server response: 

`I completed! {"host":"localhost:8080","user-agent":"GuzzleHttp/7","cache-control":"no-cache","content-length":"2"}`

I think I would be a good idea to clarify this factible usage error in Guzzle docs.

It seems to me that **the bug can be closed now.** 

Regards, xnan-dev!

**Comment by iwkse** [comment]
Hello there,
I'm having the same issues with with an authenticated call though alfresco rest api.
```
$guzzle = new GuzzleHttp\Client();
$req = $guzzle->request('GET', 
                                        'http://localhost:8080/people/-me-',
                                        'headers' => [
                                                'Accept' => 'application/json',
                                                'Authorization' => 'Basic TICKET_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
                                         ]);
```
resulted in a 401 Unauthorized

Can't get it to work yet
