### ISSUE TITLE
Multipart requests to ASP.NET "Unexpected end of MIME multipart stream" following character pattern

### ISSUE THREAD

**Issue by murphatron** [guzzle/guzzle#3008]
**Guzzle version(s) affected**: 7.4.2
**PHP version**: 7.4.15
**cURL version**: 7.29.0

**Description**  
We encountered an error in our PHP application when attempting to send a user uploaded file to a remote ASP.NET service utilizing a multipart request. After some tests of the file content, we've determined it was the terminating characters in of the file "\r\n--". This combination results in the error `Unexpected end of MIME multipart stream. MIME multipart message is not complete.` from the ASP.NET service.

This is somewhat niche and I understand if it's not something that would be fixed within this package but I felt reporting it is important. Even in the case that another developer finds this issue report and can derive their own solution.

**How to reproduce**  
```php
$client->post('the/asp/service', [
    'multipart' => [[
        'name' => 'content',
        'contents' => "hello\r\n--",
        'filename' => 'test.txt',
    ]],
]);
```

**Possible Solution**  
Append a new-line `\n` to the end of multipart content if one does not already exist corrected this problem for me.

**Comment by TimWolla** [comment]
> This is somewhat niche and I understand if it's not something that would be fixed within this package

This is a bug in the server / ASP.NET. The body as constructed by Guzzle is correct.

**Comment by xnan-dev** [comment]
Hello folks! 

Might it be worth to build some kind of optional filter for the post method to prevent this kind of problem ? It seems to me that it would be a benefit for the library users to not have to deal to this kind of errors even if the request is correct according to specs.

 (I mean, either for ASP.NET explicitly or for a more general case, something  like a regex substitution). 

Regards, xnan-dev.

**Comment by TimWolla** [comment]
> Might it be worth to build some kind of optional filter for the post method to prevent this kind of problem ?

I believe this is best solved by fixing the servers in question. If that is not possible, then you can fairly easily add the bogus trailing newline yourself if you know that the server misbehaves.

I don't believe that this is suited for some generic library implementation, because it effectively modifies the contents of the transmitted data which might or might not corrupt compressed or encrypted payload and some flag to enable the changed behavior might accidentally end up copied over from some StackOverflow answer without thinking about the consequences.
