### ISSUE TITLE
Call to undefined function GuzzleHttp\Promise\promise_for()

### ISSUE THREAD

**Issue by camohub** [guzzle/guzzle#3144]
Hi, It seems you made a BC break cause today my Cloudinary package which has Guzzle version defined like 
`"guzzlehttp/guzzle": "^6|^7",`
It throws me an error
**Call to undefined function GuzzleHttp\Promise\promise_for()**

I mean minor verions should not causes BC breaks. Can youi fix it please?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is a bug in your Cloudinary package because it was not requiring the peer dependency (using `GuzzleHttp\Promise` means you should have required explicitly the guzzle promises library). Note that those functions have been deprecated for almost three years, and you should upgrade according to this mapping: https://github.com/guzzle/promises#upgrading-from-function-api. The replacements are available in all versions since 1.4.0.

**Comment by GrahamCampbell** [comment]
https://github.com/cloudinary/cloudinary_php/pull/385 should fix your issue.
