### ISSUE TITLE
Current API docs do not match current release

### ISSUE THREAD

**Issue by jnardiello** [guzzle/guzzle#750]
Current [API](http://api.guzzlephp.org) documentation describes [version 3.7.3](http://api.guzzlephp.org/class-Guzzle.Common.Version.html).

**> 4.x** brought major changes in classes behaviours and signatures. Until new api docs are released, there should be at least a warning for users.

**Comment by Erutan409** [comment]
Forgive me for chiming in, but this seems like somewhat of a turnoff if I'm to believe any documentation isn't relevant/correct for the current release of guzzle. I've been contemplating replacing my custom-written cURL library with guzzle after seeing it being used in conjunction with elasticsearch php library.

Will it be a bumpy road ahead of me trying to adopt this library?

**Comment by GrahamCampbell** [comment]
I think you should just delete the API docs @mtdowling.

**Comment by jnardiello** [comment]
I think he should just put a disclaimer somewhere making clear that they are not addressing the current stable release.

**Comment by mtdowling** [comment]
Yeah I'll delete them

**Comment by mtdowling** [comment]
The old docs will be deleted within the next 24 hours.

**Comment by adamcameron** [comment]
Sorry to drag up an old ticket. Just fell foul of this and sank a lot of time googling for the API docs because it would never ever occur to me that an API would not have them. So just presumed I couldn't find them.

I dunno how often the API changes (ideally not very often!)... would it not be viable to generate them manually *once* and generate mark-down files and just save 'em here. Then as bits 'n' pieces of the API change, then just keep the docs up-to-date manually? At the very least ppl who find out-of-date parts of said docs could pitch in and fix 'em.

If it was down to me, I'd probably eschew all the rest of the docs, and just have API Docs. That'd be the baseline starting point. Not to be contrary but just to show "I personally don't find API docs that useful" is perhaps not the only viewpoint to consider when exposing a project to the gen. pop.

Anyway, just and idea and an observation, and I don't mean to be volunteering anyone for work they don't feel like doing.

Cheers for the otherwise excellent project!

**Comment by IvanDelsinne** [comment]
I feel the same.

I've been searching for Guzzle API docs and the only answer I found was [this SO thread](https://stackoverflow.com/questions/30874482/api-documentation-for-guzzle#32151088) whose comment "What a joke, API docs are exactly what I need right now." is the exact feeling I'm having.

API docs are very useful, maybe even more than handwritten walkthrough docs, as they can answer very technical details that could, for example, lead to easier debug and fixes.

If the sourcecode is PHPDoc'd (haven't checked rn), I may take some time working on automated doc generation but I feel it is an important work, as it also helps better coverage and API docs are a form of specification.

**Comment by rmccullagh** [comment]
Without API docs, the guzzle library is a black box. Okay, so what is the return value of getStatusCode (int, string, some type of enum, etc)? Don't know.

**Comment by stefanfisk** [comment]
For someone with as fucked an attention span as me (ADHD sucks 😿), not having a clear API reference to search means I lose track of what I'm doing again and again because I have to spend so much time and mental effort on scanning the walkthrough style docs for whatever detail I need.

Currently my solution is to open the relevant Guzzle source file a browser or editor, but that's nowhere near as readable as even the most basic phpdoc HTML export.

**Comment by WilliamVenner** [comment]
It's simply nonsense for such a popular project to have no API docs, especially when everything is already PHPDoc'd (at least to a basic extent.) Unfortunately my experience in making middleware has been a pain without them.
