### ISSUE TITLE
HTTP/Multipart, support of Content-Type and sub types headers

### ISSUE THREAD

**Issue by Nek-** [guzzle/guzzle#948]
Hello,

As it looks like you're not going to merge my PR #944 , I open an issue. Here is the related RFC link to fix in guzzle : http://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

For now, when you want to use it you need to re-implement low level query.  (you can't use the multipart classes of guzzle because the multipart headers are hardcoded)

Also I tried to extend things but important methods are private (notice: my PR respect your choice about that, even if i'm not sure it's a good one).

**Comment by mtdowling** [comment]
Thanks for the PR. I've been thinking about this one for a while, and I don't think Guzzle needs this abstraction. A multipart/form-data abstraction is provided because it handles an extremely common use case. I see that plain multipart support is useful in some cases, so perhaps a multipart abstraction that creates Guzzle streams would be a good project that people could use when they need multipart bodies. They could simple create the stream and pass it to the `body` request option.
